services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    networks:
      - taskry-network

  postgres_db:
    image: postgres:15
    hostname: postgres_db
    env_file:
      - .env.production

    ports:
      - "5432:5432"

    networks:
      - taskry-network

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task-manager"]
      interval: 5s
      timeout: 2s
      retries: 20

  db_init:
    build:
      context: .
      dockerfile: Dockerfile.dbinit
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env.production
    networks:
      - taskry-network

volumes:
  postgres_data:

networks:
  taskry-network:
    name: taskry-network
