# build stage
FROM node:24.14.0-slim AS builder

WORKDIR /app

COPY . .
RUN --mount=type=cache,target=/root/.npm npm ci --no-audit --no-fund

RUN npm run build-storybook

# runtime stage
FROM nginx:alpine

COPY --from=builder /app/storybook-static /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]