FROM node:24.14.0-slim

WORKDIR /app

COPY . .
RUN --mount=type=cache,target=/root/.npm npm ci --no-audit --no-fund

ENV NODE_ENV=production

# 3. run migrations + seed
CMD ["sh", "-c", "npm run migrate:prod && npm run seed:prod"]
