export const projectComments = [
  {
    id: 5004,
    content: "I've reviewed the initial wireframes for the checkout flow. They look clean, but we might need to add a small progress bar to indicate the user's current step in the process for better UX.",
    createdAt: "2025-01-03T11:08:32.000Z",
    senderId: "user-14",
    projectId: 41,
    taskId: null,
    parentId: null,
  },
  {
    id: 5005,
    content: "Agreed on the progress bar, David. I'll update the design files this afternoon. Bob, can you confirm the API endpoints for the new payment gateway integration?",
    createdAt: "2025-01-02T14:51:51.000Z",
    senderId: "user-16",
    projectId: 41,
    taskId: null,
    parentId: 5004,
  },
  {
    id: 5006,
    content: "Endpoints are finalized and documented in Confluence under 'Payment Integration v2.0'. We should start the backend implementation next week.",
    createdAt: "2025-01-01T11:02:04.000Z",
    senderId: "user-12",
    projectId: 41,
    taskId: null,
    parentId: 5005,
  },
  {
    id: 5007,
    content: "We need to schedule a meeting to define the A/B testing strategy for the homepage banner. Who should be included in that discussion?",
    createdAt: "2025-01-03T10:46:09.000Z",
    senderId: "user-11",
    projectId: 41,
    taskId: null,
    parentId: null,
  },
  {
    id: 5008,
    content: "Please include Grace and David for the A/B testing meeting. Their input on marketing and design is crucial.",
    createdAt: "2025-01-02T15:45:52.000Z",
    senderId: "user-12",
    projectId: 41,
    taskId: null,
    parentId: 5007,
  },
  {
    id: 5009,
    content: "I've completed the initial style guide documentation. It includes color palettes, typography, and button states. Link is in the project description.",
    createdAt: "2025-01-01T14:32:32.000Z",
    senderId: "user-20",
    projectId: 41,
    taskId: null,
    parentId: null,
  },
  {
    id: 5010,
    content: "Great job, Jack! This will significantly speed up the front-end component implementation.",
    createdAt: "2025-01-03T05:09:38.000Z",
    senderId: "user-12",
    projectId: 41,
    taskId: null,
    parentId: 5009,
  },
  {
    id: 5011,
    content: "The performance optimization phase will require dedicated QA resources to benchmark load times. Catherine, can you allocate someone for this starting next month?",
    createdAt: "2025-01-04T13:19:25.000Z",
    senderId: "user-15",
    projectId: 41,
    taskId: null,
    parentId: null,
  },
  {
    id: 5012,
    content: "The offline capability requirement for the app is critical. We should focus on using Redux Persist or similar for state management.",
    createdAt: "2025-01-03T14:59:35.000Z",
    senderId: "user-12",
    projectId: 42,
    taskId: null,
    parentId: null,
  },
  {
    id: 5013,
    content: "I've started drafting the user flow maps for the mobile app onboarding process. I'll share the first draft by EOD.",
    createdAt: "2025-01-03T05:16:15.000Z",
    senderId: "user-16",
    projectId: 42,
    taskId: null,
    parentId: null,
  },
  {
    id: 5014,
    content: "Make sure the push notification system is highly customizable for different user segments. This is a key marketing feature.",
    createdAt: "2025-01-05T11:11:49.000Z",
    senderId: "user-17",
    projectId: 42,
    taskId: null,
    parentId: null,
  },
  {
    id: 5015,
    content: "Understood, Grace. We'll utilize a service like Firebase Cloud Messaging which allows for complex targeting.",
    createdAt: "2025-01-05T11:51:23.000Z",
    senderId: "user-20",
    projectId: 42,
    taskId: null,
    parentId: 5014,
  },
  {
    id: 5016,
    content: "Regarding the security audit, we need to bring in an external consultant. Alice, can you start the procurement process for this next week?",
    createdAt: "2025-01-03T10:58:05.000Z",
    senderId: "user-15",
    projectId: 42,
    taskId: null,
    parentId: null,
  },
  {
    id: 5017,
    content: "I'll handle the procurement for the security audit. Please provide a scope of work and a budget estimate by end of day Monday.",
    createdAt: "2025-01-05T06:50:11.000Z",
    senderId: "user-11",
    projectId: 42,
    taskId: null,
    parentId: 5016,
  },
  {
    id: 5018,
    content: "The React Native choice is solid for cross-platform speed, but let's ensure we account for platform-specific UI nuances in the design phase.",
    createdAt: "2025-01-04T07:36:41.000Z",
    senderId: "user-14",
    projectId: 42,
    taskId: null,
    parentId: null,
  },
  {
    id: 5019,
    content: "We must prioritize the real-time data synchronization. What backend technology are we leaning toward for handling websockets/live updates?",
    createdAt: "2025-01-03T05:12:55.000Z",
    senderId: "user-13",
    projectId: 42,
    taskId: null,
    parentId: null,
  },
  {
    id: 5027,
    content: "Grace, I've reviewed the campaign strategy. The goal of a 25% increase in lead generation is ambitious but achievable. We need solid reporting metrics in place from day one.",
    createdAt: "2025-01-05T11:44:49.000Z",
    senderId: "user-15",
    projectId: 43,
    taskId: null,
    parentId: null,
  },
  {
    id: 5028,
    content: "I'll set up the GA4 (Google Analytics 4) conversion tracking and the HubSpot integration today to ensure data accuracy for the reports.",
    createdAt: "2025-01-05T09:21:36.000Z",
    senderId: "user-17",
    projectId: 43,
    taskId: null,
    parentId: 5027,
  },
  {
    id: 5029,
    content: "The content team requires the finalized list of SEO target keywords for the first batch of blog posts by Friday morning.",
    createdAt: "2025-01-05T06:04:12.000Z",
    senderId: "user-19",
    projectId: 43,
    taskId: null,
    parentId: null,
  },
  {
    id: 5030,
    content: "Frank and David, can you prioritize the creative assets (banners, video snippets) for the paid social campaign? We aim to launch the ads on Monday.",
    createdAt: "2025-01-04T03:35:58.000Z",
    senderId: "user-17",
    projectId: 43,
    taskId: null,
    parentId: null,
  },
  {
    id: 5031,
    content: "I've allocated Jack to assist with the technical implementation of the email campaign templates to ensure they are fully responsive.",
    createdAt: "2025-01-03T12:09:59.000Z",
    senderId: "user-12",
    projectId: 43,
    taskId: null,
    parentId: 5030,
  },
  {
    id: 5032,
    content: "Creative assets are in progress. David is handling the static banners, and I'm finalizing the video storyboard for Frank to review.",
    createdAt: "2025-01-06T12:44:18.000Z",
    senderId: "user-16",
    projectId: 43,
    taskId: null,
    parentId: 5030,
  },
  {
    id: 5033,
    content: "Remember to include A/B testing variations for all email subject lines to maximize open rates.",
    createdAt: "2025-01-06T03:40:08.000Z",
    senderId: "user-14",
    projectId: 43,
    taskId: null,
    parentId: 5031,
  },
  {
    id: 5034,
    content: "Confirmed the SEO keyword list is finalized and shared in the project's documentation folder. Content team can begin drafting.",
    createdAt: "2025-01-03T09:21:55.000Z",
    senderId: "user-17",
    projectId: 43,
    taskId: null,
    parentId: 5029,
  },
  {
    id: 5035,
    content: "The HR Portal upgrade's main concern is data security and compliance. We need to map out the data flow for PII (Personally Identifiable Information) immediately.",
    createdAt: "2025-01-07T04:24:55.000Z",
    senderId: "user-15",
    projectId: 44,
    taskId: null,
    parentId: null,
  },
  {
    id: 5036,
    content: "Henry, I've created a baseline architecture proposal using AWS Cognito for authentication and encryption for all sensitive fields. Please review.",
    createdAt: "2025-01-05T11:13:17.000Z",
    senderId: "user-12",
    projectId: 44,
    taskId: null,
    parentId: 5035,
  },
  {
    id: 5037,
    content: "The automated time-off request module needs clear approval hierarchies defined by Henry's team before coding can begin on that feature.",
    createdAt: "2025-01-05T04:50:44.000Z",
    senderId: "user-20",
    projectId: 44,
    taskId: null,
    parentId: null,
  },
  {
    id: 5038,
    content: "I'll provide the final sign-off rules for time-off requests by end of day tomorrow. They follow the standard corporate structure.",
    createdAt: "2025-01-07T07:49:22.000Z",
    senderId: "user-18",
    projectId: 44,
    taskId: null,
    parentId: 5037,
  },
  {
    id: 5039,
    content: "Who is responsible for the integration with the existing payroll system (Vendor: ADP)? We need to get API access and documentation.",
    createdAt: "2025-01-05T14:20:31.000Z",
    senderId: "user-11",
    projectId: 44,
    taskId: null,
    parentId: null,
  },
  {
    id: 5040,
    content: "Ivy, as the finance contact, could you coordinate with the ADP technical support team to provide us with the necessary integration keys and docs?",
    createdAt: "2025-01-06T05:05:28.000Z",
    senderId: "user-18",
    projectId: 44,
    taskId: null,
    parentId: 5039,
  },
  {
    id: 5041,
    content: "I am reaching out to ADP now. I'll forward the API documentation to Bob and Jack as soon as I receive it.",
    createdAt: "2025-01-06T13:14:12.000Z",
    senderId: "user-19",
    projectId: 44,
    taskId: null,
    parentId: 5040,
  },
  {
    id: 5042,
    content: "The design mockups for the new performance review tracking interface are complete and shared in the project folder. Feedback welcome, especially from the QA team.",
    createdAt: "2025-01-08T09:30:38.000Z",
    senderId: "user-14",
    projectId: 44,
    taskId: null,
    parentId: null,
  },
  {
    id: 5043,
    content: "I noticed a potential accessibility issue (WCAG 2.1) with the color contrast in the performance tracking dashboard. We need to adjust the primary blue shade.",
    createdAt: "2025-01-05T03:53:14.000Z",
    senderId: "user-13",
    projectId: 44,
    taskId: null,
    parentId: 5042,
  },
  {
    id: 5044,
    content: "The color palette section is approved. Frank, can you ensure all hex and RGB values are accurately documented for both digital and print usage?",
    createdAt: "2025-01-12T10:22:25.000Z",
    senderId: "user-14",
    projectId: 45,
    taskId: null,
    parentId: null,
  },
  {
    id: 5045,
    content: "Confirmed. I'm double-checking the CMYK conversions for the secondary brand colors now. Everything will be finalized in the asset package by EOD.",
    createdAt: "2025-01-12T08:19:42.000Z",
    senderId: "user-16",
    projectId: 45,
    taskId: null,
    parentId: 5044,
  },
  {
    id: 5046,
    content: "I've drafted the 'Voice and Tone' guidelines for external marketing materials. Grace, please review this draft to ensure alignment with Q4 campaign messaging.",
    createdAt: "2025-01-11T12:43:07.000Z",
    senderId: "user-19",
    projectId: 45,
    taskId: null,
    parentId: null,
  },
  {
    id: 5047,
    content: "The Voice and Tone document looks great, Ivy. Just one minor adjustment: emphasize the 'user-centric' language more in the product descriptions.",
    createdAt: "2025-01-11T04:33:40.000Z",
    senderId: "user-17",
    projectId: 45,
    taskId: null,
    parentId: 5046,
  },
  {
    id: 5048,
    content: "Jack is finalizing the SVG files for all logo variations, including negative space usage and minimum size requirements. We should upload them to the shared drive by Tuesday.",
    createdAt: "2025-01-09T15:42:09.000Z",
    senderId: "user-14",
    projectId: 45,
    taskId: null,
    parentId: null,
  },
  {
    id: 5049,
    content: "The typography section needs a clear hierarchy scale for H1-H6 headers for the new e-commerce platform. Can we add guidance for mobile implementation?",
    createdAt: "2025-01-11T10:06:49.000Z",
    senderId: "user-20",
    projectId: 45,
    taskId: null,
    parentId: 5048,
  },
  {
    id: 5050,
    content: "I've added the mobile typography scaling specs (using a modular scale approach) and updated the document. Thanks for the catch, Jack.",
    createdAt: "2025-01-11T08:51:14.000Z",
    senderId: "user-16",
    projectId: 45,
    taskId: null,
    parentId: 5049,
  },
  {
    id: 5051,
    content: "Since this project is wrapping up, Catherine, please ensure the final guide passes all internal quality checks for consistency and completeness before we mark it as completed.",
    createdAt: "2025-01-10T13:37:52.000Z",
    senderId: "user-11",
    projectId: 45,
    taskId: null,
    parentId: null,
  },
  {
    id: 5052,
    content: "The primary goal is zero downtime during cutover. Bob, can you propose a specific migration strategy (e.g., blue/green deployment) for the database?",
    createdAt: "2025-01-13T14:16:12.000Z",
    senderId: "user-15",
    projectId: 46,
    taskId: null,
    parentId: null,
  },
  {
    id: 5053,
    content: "I recommend a phased, iterative migration using a **strangler figure pattern** to decouple microservices one by one, minimizing risk to the core app.",
    createdAt: "2025-01-14T05:18:44.000Z",
    senderId: "user-12",
    projectId: 46,
    taskId: null,
    parentId: 5052,
  },
  {
    id: 5054,
    content: "We need a detailed breakdown of the costs associated with the new AWS infrastructure, including data transfer fees and reserved instances. Ivy, can you help track this budget?",
    createdAt: "2025-01-16T11:11:58.000Z",
    senderId: "user-11",
    projectId: 46,
    taskId: null,
    parentId: null,
  },
  {
    id: 5055,
    content: "I'm setting up a real-time budget tracker linked to the AWS cost explorer. I will share the link with the core team by Monday.",
    createdAt: "2025-01-14T15:58:08.000Z",
    senderId: "user-19",
    projectId: 46,
    taskId: null,
    parentId: 5054,
  },
  {
    id: 5056,
    content: "The security audit for the new cloud environment is mandatory. I've contacted Henry to discuss allocating resources for the penetration testing phase.",
    createdAt: "2025-01-16T03:53:26.000Z",
    senderId: "user-13",
    projectId: 46,
    taskId: null,
    parentId: null,
  },
  {
    id: 5057,
    content: "Before we begin the migration, we must finalize the Disaster Recovery Plan (DRP) documentation. It needs to cover RTO and RPO metrics for all critical services.",
    createdAt: "2025-01-13T06:48:06.000Z",
    senderId: "user-15",
    projectId: 46,
    taskId: null,
    parentId: null,
  },
  {
    id: 5058,
    content: "I'm drafting the DRP now, focusing on a multi-region setup for high availability. Estimated RTO is 4 hours, RPO is 15 minutes. Review ready on Wednesday.",
    createdAt: "2025-01-14T04:59:14.000Z",
    senderId: "user-12",
    projectId: 46,
    taskId: null,
    parentId: 5057,
  },
  {
    id: 5059,
    content: "Henry confirmed the penetration testing can be sourced externally. We need to define the scope based on the microservices being migrated first.",
    createdAt: "2025-01-14T05:20:54.000Z",
    senderId: "user-13",
    projectId: 46,
    taskId: null,
    parentId: 5056,
  },
  {
    id: 5060,
    content: "The legacy servers must remain active as read-replicas until the new cloud system passes full stress testing and UAT. This is crucial for rollback capability.",
    createdAt: "2025-01-16T12:22:32.000Z",
    senderId: "user-11",
    projectId: 46,
    taskId: null,
    parentId: null,
  },
  {
    id: 5061,
    content: "The main focus for V2 is query performance. Bob, can we look into optimizing the database schema or utilizing a dedicated analytics database like Redshift?",
    createdAt: "2025-01-19T07:11:21.000Z",
    senderId: "user-14",
    projectId: 47,
    taskId: null,
    parentId: null,
  },
  {
    id: 5062,
    content: "I recommend prototyping with a **data cube solution** (OLAP) to handle the complex aggregated queries faster. I'll share a proof of concept by the end of the week.",
    createdAt: "2025-01-18T10:47:56.000Z",
    senderId: "user-12",
    projectId: 47,
    taskId: null,
    parentId: 5061,
  },
  {
    id: 5063,
    content: "We need final input from Grace on which marketing funnel metrics are most critical for visualization on the leadership dashboard.",
    createdAt: "2025-01-20T03:15:53.000Z",
    senderId: "user-11",
    projectId: 47,
    taskId: null,
    parentId: null,
  },
  {
    id: 5064,
    content: "Please prioritize **Lead-to-Opportunity conversion rate** and **Cost Per Acquisition (CPA)** visuals for the leadership view. Those are key.",
    createdAt: "2025-01-19T12:20:28.000Z",
    senderId: "user-17",
    projectId: 47,
    taskId: null,
    parentId: 5063,
  },
  {
    id: 5065,
    content: "David, the new visualization components must be fully compliant with accessibility standards (WCAG 2.1) for colorblind users, given the high data density.",
    createdAt: "2025-01-18T13:03:26.000Z",
    senderId: "user-13",
    projectId: 47,
    taskId: null,
    parentId: null,
  },
  {
    id: 5066,
    content: "I've started integrating the new customer interaction data source. It requires mapping 15 new fields into our central data warehouse schema.",
    createdAt: "2025-01-20T13:58:02.000Z",
    senderId: "user-20",
    projectId: 47,
    taskId: null,
    parentId: null,
  },
  {
    id: 5067,
    content: "Can we ensure the customizable reporting feature allows for exporting data in multiple formats (CSV, PDF)? This is a strict requirement from the finance team.",
    createdAt: "2025-01-21T05:18:28.000Z",
    senderId: "user-19",
    projectId: 47,
    taskId: null,
    parentId: null,
  },
  {
    id: 5068,
    content: "Confirmed. I've designed the export functionality to support CSV and PDF. The UI mockups are updated in the Figma file.",
    createdAt: "2025-01-20T11:18:04.000Z",
    senderId: "user-14",
    projectId: 47,
    taskId: null,
    parentId: 5067,
  },
  {
    id: 5069,
    content: "For the in-app chat, we need to decide on a service provider. Looking at Zendesk vs. Intercom. What are the license costs and integration complexity for each?",
    createdAt: "2025-01-21T11:23:10.000Z",
    senderId: "user-20",
    projectId: 48,
    taskId: null,
    parentId: null,
  },
  {
    id: 5070,
    content: "I've started comparing Intercom and Zendesk based on our security requirements and Henry's budget guidance. Will share the summary by tomorrow.",
    createdAt: "2025-01-23T12:07:58.000Z",
    senderId: "user-11",
    projectId: 48,
    taskId: null,
    parentId: 5069,
  },
  {
    id: 5071,
    content: "The integrated knowledge base search must be lightning fast and support natural language queries. We should use a dedicated search service, not just a database query.",
    createdAt: "2025-01-21T14:41:34.000Z",
    senderId: "user-12",
    projectId: 48,
    taskId: null,
    parentId: null,
  },
  {
    id: 5072,
    content: "I recommend using **Elasticsearch** for the knowledge base search due to its speed and full-text search capabilities. I can set up a cluster for testing next week.",
    createdAt: "2025-01-24T06:04:21.000Z",
    senderId: "user-15",
    projectId: 48,
    taskId: null,
    parentId: 5071,
  },
  {
    id: 5073,
    content: "The personalized user feed feature requires defining clear **personalization rules** based on user history and preferences. Grace, can you define the initial logic?",
    createdAt: "2025-01-21T10:40:20.000Z",
    senderId: "user-20",
    projectId: 48,
    taskId: null,
    parentId: null,
  },
  {
    id: 5074,
    content: "Personalization rules should prioritize content based on last three product views and geographic location. I'll document the initial five rule sets today.",
    createdAt: "2025-01-22T09:25:36.000Z",
    senderId: "user-17",
    projectId: 48,
    taskId: null,
    parentId: 5073,
  },
  {
    id: 5075,
    content: "The regression testing plan for the Mobile App Feature Expansion needs to be comprehensive. We must test all core functionalities on both iOS 17 and Android 14.",
    createdAt: "2025-01-23T09:39:55.000Z",
    senderId: "user-13",
    projectId: 48,
    taskId: null,
    parentId: null,
  },
  {
    id: 5076,
    content: "Frank, can you create high-fidelity mockups for the new in-app chat interface? It needs to seamlessly integrate with the existing mobile design language.",
    createdAt: "2025-01-24T08:03:24.000Z",
    senderId: "user-14",
    projectId: 48,
    taskId: null,
    parentId: null,
  },
  {
    id: 5077,
    content: "The backend API update for the user feed requires careful versioning to avoid breaking the existing mobile clients. We must use API v2.",
    createdAt: "2025-01-24T09:09:11.000Z",
    senderId: "user-12",
    projectId: 48,
    taskId: null,
    parentId: 5073,
  },
  {
    id: 5078,
    content: "The first step is engaging the external penetration testing firm. Henry, can you confirm the contract with 'SecureTech Solutions' is active and they have the necessary scope documents?",
    createdAt: "2025-01-22T11:52:10.000Z",
    senderId: "user-13",
    projectId: 49,
    taskId: null,
    parentId: null,
  },
  {
    id: 5079,
    content: "Contract is signed, and access details for the staging environment will be provided to SecureTech by EOD today. We emphasized the zero-knowledge requirement for their initial assessment.",
    createdAt: "2025-01-23T05:07:12.000Z",
    senderId: "user-18",
    projectId: 49,
    taskId: null,
    parentId: 5078,
  },
  {
    id: 5080,
    content: "We need to run our internal **vulnerability scan** (using Nessus) across all microservices before the external testers begin to catch low-hanging fruit and optimize their time.",
    createdAt: "2025-01-24T07:49:38.000Z",
    senderId: "user-12",
    projectId: 49,
    taskId: null,
    parentId: null,
  },
  {
    id: 5081,
    content: "Bob, I've scheduled the Nessus scan for tonight during off-peak hours. Results will be available in the shared audit folder by morning.",
    createdAt: "2025-01-25T06:43:22.000Z",
    senderId: "user-20",
    projectId: 49,
    taskId: null,
    parentId: 5080,
  },
  {
    id: 5082,
    content: "I'll be reviewing all **access control policies** (RBAC) across the cloud infrastructure and the internal user management system. Need current documentation from Alice.",
    createdAt: "2025-01-24T14:53:17.000Z",
    senderId: "user-15",
    projectId: 49,
    taskId: null,
    parentId: null,
  },
  {
    id: 5083,
    content: "The documentation for Role-Based Access Control is attached to this project. Focus particularly on restricting access to the finance and HR portals (Project 44).",
    createdAt: "2025-01-23T14:36:42.000Z",
    senderId: "user-11",
    projectId: 49,
    taskId: null,
    parentId: 5082,
  },
  {
    id: 5084,
    content: "Any critical findings must be reported immediately and prioritized for resolution within 48 hours of discovery. Catherine, please monitor the external audit channel.",
    createdAt: "2025-01-23T05:22:04.000Z",
    senderId: "user-15",
    projectId: 49,
    taskId: null,
    parentId: null,
  },
  {
    id: 5085,
    content: "Confirmed monitoring the audit channel. We should have a dedicated triage meeting immediately after the final report is delivered next week.",
    createdAt: "2025-01-24T07:54:16.000Z",
    senderId: "user-13",
    projectId: 49,
    taskId: null,
    parentId: 5084,
  },
  {
    id: 5086,
    content: "Frank, let's start with wireframes focusing on the **conversion funnel** (Clear CTA, minimal fields) before diving into the high-fidelity mockups.",
    createdAt: "2025-01-24T08:17:22.000Z",
    senderId: "user-14",
    projectId: 50,
    taskId: null,
    parentId: null,
  },
  {
    id: 5087,
    content: "Agreed, David. I'll also ensure all design elements strictly follow the new Brand Style Guide (Project 45) for consistency.",
    createdAt: "2025-01-26T11:20:06.000Z",
    senderId: "user-16",
    projectId: 50,
    taskId: null,
    parentId: 5086,
  },
  {
    id: 5088,
    content: "Grace, we need the finalized launch messaging and a list of primary, secondary, and tertiary SEO keywords for the page content by the end of next week.",
    createdAt: "2025-01-24T08:21:26.000Z",
    senderId: "user-11",
    projectId: 50,
    taskId: null,
    parentId: null,
  },
  {
    id: 5089,
    content: "Keywords and messaging will be prioritized. I'll schedule a quick content review with Ivy to ensure legal compliance on product claims.",
    createdAt: "2025-01-25T08:18:41.000Z",
    senderId: "user-17",
    projectId: 50,
    taskId: null,
    parentId: 5088,
  },
  {
    id: 5090,
    content: "The front-end build must be optimized for loading speed (Core Web Vitals). We should target a Lighthouse score of 95+.",
    createdAt: "2025-01-23T13:02:49.000Z",
    senderId: "user-20",
    projectId: 50,
    taskId: null,
    parentId: null,
  },
  {
    id: 5091,
    content: "Jack, let's use a static site generator or a highly optimized framework like Next.js for the build to hit that speed target.",
    createdAt: "2025-01-23T08:30:08.000Z",
    senderId: "user-12",
    projectId: 50,
    taskId: null,
    parentId: 5090,
  },
  {
    id: 5092,
    content: "I need to ensure the landing page is rigorously tested for responsiveness across all major mobile screen sizes, as most traffic will be mobile-first.",
    createdAt: "2025-01-26T08:00:42.000Z",
    senderId: "user-13",
    projectId: 50,
    taskId: null,
    parentId: null,
  },
  {
    id: 5093,
    content: "Can we integrate a pre-launch analytics snippet (e.g., Google Tag Manager) early in the development process for test tracking?",
    createdAt: "2025-01-26T09:16:47.000Z",
    senderId: "user-17",
    projectId: 50,
    taskId: null,
    parentId: 5090,
  },
  {
    id: 5094,
    content: "The most challenging part of this project will be the **real-time integration with the ERP system**. Bob, can you lead the effort to define the API gateway for read/write operations?",
    createdAt: "2025-01-28T03:41:48.000Z",
    senderId: "user-11",
    projectId: 51,
    taskId: null,
    parentId: null,
  },
  {
    id: 5095,
    content: "I'll start architecting the middleware layer to handle the ERP integration. We should use a message queue (like Kafka) to ensure reliable data sync, especially with offline mode involved.",
    createdAt: "2025-01-30T10:48:44.000Z",
    senderId: "user-12",
    projectId: 51,
    taskId: null,
    parentId: 5094,
  },
  {
    id: 5096,
    content: "For the **geo-location tracking**, we need to confirm the required tracking granularity and the acceptable battery usage limits on the field agents' mobile devices.",
    createdAt: "2025-01-28T13:19:53.000Z",
    senderId: "user-20",
    projectId: 51,
    taskId: null,
    parentId: null,
  },
  {
    id: 5097,
    content: "Frank, I need initial mockups for the **offline mode UI**. It needs to clearly communicate connection status and pending sync activities to the user.",
    createdAt: "2025-01-27T13:01:57.000Z",
    senderId: "user-14",
    projectId: 51,
    taskId: null,
    parentId: null,
  },
  {
    id: 5098,
    content: "I've reviewed the requirements. The data validation needs to be robust, including client-side validation for form completion before allowing offline saving.",
    createdAt: "2025-01-28T15:06:30.000Z",
    senderId: "user-13",
    projectId: 51,
    taskId: null,
    parentId: null,
  },
  {
    id: 5099,
    content: "I'll prototype the geo-location feature using the device's native GPS and incorporate power-saving modes when the app is backgrounded.",
    createdAt: "2025-01-27T06:18:43.000Z",
    senderId: "user-12",
    projectId: 51,
    taskId: null,
    parentId: 5096,
  },
  {
    id: 5100,
    content: "Mockups for the offline UI are complete. I used a clear banner notification and added a 'Sync Status' indicator to the main dashboard.",
    createdAt: "2025-01-30T14:44:08.000Z",
    senderId: "user-16",
    projectId: 51,
    taskId: null,
    parentId: 5097,
  },
  {
    id: 5101,
    content: "The goal is to reduce manual processing by 40%. Henry, can you map out the current process flow for new hires so we can identify specific bottlenecks to automate?",
    createdAt: "2025-02-03T07:52:18.000Z",
    senderId: "user-11",
    projectId: 52,
    taskId: null,
    parentId: null,
  },
  {
    id: 5102,
    content: "I've documented the current 12-step flow. The biggest bottleneck is the physical signing and scanning of documents. We must focus on digital form signatures.",
    createdAt: "2025-02-02T07:36:31.000Z",
    senderId: "user-18",
    projectId: 52,
    taskId: null,
    parentId: 5101,
  },
  {
    id: 5103,
    content: "The new flow needs to fully integrate with the HR portal (Project 44) for automated profile creation and task assignment (onboarding checklists).",
    createdAt: "2025-02-01T03:15:23.000Z",
    senderId: "user-12",
    projectId: 52,
    taskId: null,
    parentId: 5102,
  },
  {
    id: 5104,
    content: "David, please prioritize a clean, welcoming, and intuitive UI for the new hire experience. First impressions are crucial for satisfaction scores.",
    createdAt: "2025-02-02T09:13:01.000Z",
    senderId: "user-15",
    projectId: 52,
    taskId: null,
    parentId: null,
  },
  {
    id: 5105,
    content: "I'll need to coordinate with Ivy to ensure the digital forms are compliant with all relevant labor laws and data retention policies before deployment.",
    createdAt: "2025-02-01T14:19:59.000Z",
    senderId: "user-13",
    projectId: 52,
    taskId: null,
    parentId: null,
  },
  {
    id: 5106,
    content: "I'm starting the design process for the new onboarding dashboard. Will share mood boards focusing on professionalism and ease-of-use by EOD.",
    createdAt: "2025-02-03T05:50:00.000Z",
    senderId: "user-14",
    projectId: 52,
    taskId: null,
    parentId: 5104,
  },
  {
    id: 5107,
    content: "Grace, I've compiled the initial list of **core business keywords** for Q2. We need to segment them based on high, medium, and low competition.",
    createdAt: "2025-02-03T08:01:34.000Z",
    senderId: "user-14",
    projectId: 53,
    taskId: null,
    parentId: null,
  },
  {
    id: 5108,
    content: "Thanks, David. I'll use that segmentation to finalize the content calendar. We need a minimum of 8 long-form articles and 4 downloadable guides this quarter.",
    createdAt: "2025-02-02T09:01:06.000Z",
    senderId: "user-17",
    projectId: 53,
    taskId: null,
    parentId: 5107,
  },
  {
    id: 5109,
    content: "I recommend focusing the first month on **top-of-funnel content** (educational articles) to capture a wider organic audience.",
    createdAt: "2025-02-02T15:05:13.000Z",
    senderId: "user-19",
    projectId: 53,
    taskId: null,
    parentId: null,
  },
  {
    id: 5110,
    content: "We must ensure all new content is designed for excellent user experience—fast loading, mobile-friendly, and engaging formatting. Frank, can you consult on the formatting standards?",
    createdAt: "2025-02-01T08:59:43.000Z",
    senderId: "user-11",
    projectId: 53,
    taskId: null,
    parentId: null,
  },
  {
    id: 5111,
    content: "I'll prepare a template for the long-form articles that includes best practices for readability and image optimization to support SEO efforts.",
    createdAt: "2025-02-02T10:15:24.000Z",
    senderId: "user-16",
    projectId: 53,
    taskId: null,
    parentId: 5110,
  },
  {
    id: 5112,
    content: "The **backlink acquisition** strategy needs to target authoritative domains only. Grace, we should list 50 target sites for outreach next week.",
    createdAt: "2025-02-04T14:11:52.000Z",
    senderId: "user-17",
    projectId: 53,
    taskId: null,
    parentId: null,
  },
  {
    id: 5113,
    content: "We need dedicated tracking in GA4 for organic traffic segmentation and keyword ranking improvements to measure the 30% success metric.",
    createdAt: "2025-02-01T05:52:25.000Z",
    senderId: "user-20",
    projectId: 53,
    taskId: null,
    parentId: null,
  },
  {
    id: 5114,
    content: "Catherine, please set up a recurring task to review all published content for broken links, grammatical errors, and factual accuracy before promotion.",
    createdAt: "2025-02-03T08:47:29.000Z",
    senderId: "user-11",
    projectId: 53,
    taskId: null,
    parentId: null,
  },
  {
    id: 5115,
    content: "Confirmed. I'm adding a mandatory QA check for all content assets before they go live on the site.",
    createdAt: "2025-02-03T15:41:19.000Z",
    senderId: "user-13",
    projectId: 53,
    taskId: null,
    parentId: 5114,
  },
  {
    id: 5116,
    content: "The priority for the UI Kit Refresh is **WCAG 2.1 compliance**. Catherine, please provide the specific checklist for color contrast and focus states for the new components.",
    createdAt: "2025-02-07T06:44:33.000Z",
    senderId: "user-16",
    projectId: 54,
    taskId: null,
    parentId: null,
  },
  {
    id: 5117,
    content: "I've drafted the QA checklist for accessibility, focusing on contrast ratios (minimum AA for normal text) and keyboard navigation. Document link shared.",
    createdAt: "2025-02-07T06:32:40.000Z",
    senderId: "user-13",
    projectId: 54,
    taskId: null,
    parentId: 5116,
  },
  {
    id: 5118,
    content: "Frank and David, we need a clear standard for the **Dark Mode palette**. Ensure sufficient luminance contrast while avoiding pure white/black extremes to reduce eye strain.",
    createdAt: "2025-02-08T15:13:17.000Z",
    senderId: "user-15",
    projectId: 54,
    taskId: null,
    parentId: null,
  },
  {
    id: 5119,
    content: "I've started documenting the new component states and usage guidelines in Zeroheight. The documentation structure will mirror the existing component library.",
    createdAt: "2025-02-06T07:31:38.000Z",
    senderId: "user-14",
    projectId: 54,
    taskId: null,
    parentId: null,
  },
  {
    id: 5120,
    content: "The design system must include clear usage rules for all icons and illustrations. Jack, can you create a set of optimized SVG assets based on the new palette?",
    createdAt: "2025-02-06T13:01:58.000Z",
    senderId: "user-16",
    projectId: 54,
    taskId: null,
    parentId: null,
  },
  {
    id: 5121,
    content: "Confirmed. I'll ensure the SVG assets are clean, compressed, and support the dynamic color changes required for the dark mode implementation.",
    createdAt: "2025-02-07T12:15:24.000Z",
    senderId: "user-20",
    projectId: 54,
    taskId: null,
    parentId: 5120,
  },
  {
    id: 5122,
    content: "We need Alice to coordinate communication with the front-end development teams across all projects to ensure timely adoption of the refreshed UI kit.",
    createdAt: "2025-02-09T08:53:52.000Z",
    senderId: "user-15",
    projectId: 54,
    taskId: null,
    parentId: null,
  },
  {
    id: 5123,
    content: "I'll organize a kickoff meeting next week to present the new UI Kit standards and address any implementation questions from the teams.",
    createdAt: "2025-02-09T06:51:01.000Z",
    senderId: "user-11",
    projectId: 54,
    taskId: null,
    parentId: 5122,
  },
  {
    id: 5124,
    content: "The transition to a microservices architecture is key for scalability. I propose starting with isolating the 'User Authentication' service as the first microservice.",
    createdAt: "2025-02-12T06:59:21.000Z",
    senderId: "user-12",
    projectId: 55,
    taskId: null,
    parentId: null,
  },
  {
    id: 5125,
    content: "Agreed on the Authentication service being first. This isolation will require careful planning for API routing and eventual consistency with the legacy system during the transition.",
    createdAt: "2025-02-13T08:29:33.000Z",
    senderId: "user-15",
    projectId: 55,
    taskId: null,
    parentId: 5124,
  },
  {
    id: 5126,
    content: "We must define strict SLAs (Service Level Agreements) for the new microservices, especially regarding response times. What's the target latency for the Authentication service?",
    createdAt: "2025-02-14T05:23:07.000Z",
    senderId: "user-13",
    projectId: 55,
    taskId: null,
    parentId: null,
  },
  {
    id: 5127,
    content: "The target latency for the Authentication service should be under 50ms, with 99.9% uptime. This requires a strong focus on optimized data caching.",
    createdAt: "2025-02-13T12:25:31.000Z",
    senderId: "user-12",
    projectId: 55,
    taskId: null,
    parentId: 5126,
  },
  {
    id: 5128,
    content: "Alice, the project budget needs to account for new infrastructure costs associated with containerization (Docker/Kubernetes) and inter-service communication tools.",
    createdAt: "2025-02-13T07:17:02.000Z",
    senderId: "user-19",
    projectId: 55,
    taskId: null,
    parentId: null,
  },
  {
    id: 5129,
    content: "I'll create a detailed cost projection with Ivy. Separately, we need to begin writing the integration tests for the remaining core services to establish a baseline before the change.",
    createdAt: "2025-02-14T07:04:14.000Z",
    senderId: "user-11",
    projectId: 55,
    taskId: null,
    parentId: 5128,
  },
  {
    id: 5130,
    content: "The documentation for the new API structure (OpenAPI/Swagger) must be kept up-to-date in real time. Jack, can you integrate automatic documentation generation into the CI/CD pipeline?",
    createdAt: "2025-02-14T06:15:27.000Z",
    senderId: "user-12",
    projectId: 55,
    taskId: null,
    parentId: null,
  },
  {
    id: 5131,
    content: "Confirmed. I'm setting up the CI/CD pipeline integration now to auto-generate the Swagger documentation on every successful build and deploy.",
    createdAt: "2025-02-13T10:30:00.000Z",
    senderId: "user-20",
    projectId: 55,
    taskId: null,
    parentId: 5130,
  },
  {
    id: 5132,
    content: "The priority for the Client Feedback Mechanism is defining the **data structure** for the survey responses so it integrates seamlessly with Analytics Dashboard V2 (Project 47).",
    createdAt: "2025-02-16T06:46:14.000Z",
    senderId: "user-13",
    projectId: 56,
    taskId: null,
    parentId: null,
  },
  {
    id: 5133,
    content: "I've drafted the required JSON schema for the feedback data, including fields for touchpoint, rating, and user ID. This aligns with the new data warehouse structure.",
    createdAt: "2025-02-15T11:05:33.000Z",
    senderId: "user-12",
    projectId: 56,
    taskId: null,
    parentId: 5132,
  },
  {
    id: 5134,
    content: "Frank, we need a lightweight, non-intrusive design for the **website widget**. It should follow the UI Kit Refresh (Project 54) standards, including dark mode support.",
    createdAt: "2025-02-15T13:48:43.000Z",
    senderId: "user-14",
    projectId: 56,
    taskId: null,
    parentId: null,
  },
  {
    id: 5135,
    content: "I'll prototype a minimal widget design that only appears after the user completes a core action or spends a defined amount of time on a page, to minimize disruption.",
    createdAt: "2025-02-15T07:20:40.000Z",
    senderId: "user-16",
    projectId: 56,
    taskId: null,
    parentId: 5134,
  },
  {
    id: 5136,
    content: "Grace, which specific **post-service email touchpoints** are we prioritizing for the automated survey deployment initially (e.g., Purchase completion, Ticket closure)?",
    createdAt: "2025-02-14T13:06:44.000Z",
    senderId: "user-11",
    projectId: 56,
    taskId: null,
    parentId: null,
  },
  {
    id: 5137,
    content: "We must prioritize the 'Order Delivered' email and the 'Support Ticket Resolved' email. These two points provide the most actionable data.",
    createdAt: "2025-02-16T12:10:49.000Z",
    senderId: "user-17",
    projectId: 56,
    taskId: null,
    parentId: 5136,
  },
  {
    id: 5138,
    content: "The **data piping** requires robust error logging. Jack, can you integrate the logging pipeline to capture any failed submissions or corrupted data packets?",
    createdAt: "2025-02-16T05:48:23.000Z",
    senderId: "user-15",
    projectId: 56,
    taskId: null,
    parentId: null,
  },
  {
    id: 5139,
    content: "I'm integrating Prometheus for metric collection and setting up automatic alerts for any data pipeline failure exceeding a 1% error rate.",
    createdAt: "2025-02-14T11:53:03.000Z",
    senderId: "user-20",
    projectId: 56,
    taskId: null,
    parentId: 5138,
  },
  {
    id: 5140,
    content: "The primary challenge for the Annual Financial Reporting System is pulling data accurately from multiple siloed databases. We need a unified data view.",
    createdAt: "2025-02-18T14:39:40.000Z",
    senderId: "user-19",
    projectId: 57,
    taskId: null,
    parentId: null,
  },
  {
    id: 5141,
    content: "I recommend using an ETL process to harmonize the data into a single staging database before report generation. This minimizes the risk of compliance errors.",
    createdAt: "2025-02-16T08:54:22.000Z",
    senderId: "user-12",
    projectId: 57,
    taskId: null,
    parentId: 5140,
  },
  {
    id: 5142,
    content: "The system requires a full, immutable **audit trail** for every transaction and report change to comply with international accounting standards. This cannot be overlooked.",
    createdAt: "2025-02-16T07:42:48.000Z",
    senderId: "user-15",
    projectId: 57,
    taskId: null,
    parentId: null,
  },
  {
    id: 5143,
    content: "We need Henry to confirm the specific **international accounting standards** (e.g., IFRS, GAAP) that the final reports must adhere to.",
    createdAt: "2025-02-16T12:24:30.000Z",
    senderId: "user-13",
    projectId: 57,
    taskId: null,
    parentId: 5142,
  },
  {
    id: 5144,
    content: "All reports must be compliant with both US GAAP and IFRS due to our global operations. The system must support generating reports in either format.",
    createdAt: "2025-02-18T14:44:31.000Z",
    senderId: "user-18",
    projectId: 57,
    taskId: null,
    parentId: 5143,
  },
  {
    id: 5145,
    content: "The security protocol for accessing and generating these financial reports must be the highest level, requiring multi-factor authentication and strict RBAC controls.",
    createdAt: "2025-02-16T14:54:14.000Z",
    senderId: "user-11",
    projectId: 57,
    taskId: null,
    parentId: null,
  },
  {
    id: 5146,
    content: "I've started drafting the report templates. We need final confirmation on the required visual charts and key performance indicators (KPIs) from leadership before finalizing the design.",
    createdAt: "2025-02-18T09:02:25.000Z",
    senderId: "user-14",
    projectId: 57,
    taskId: null,
    parentId: null,
  },
  {
    id: 5147,
    content: "The first step for the Video Ad Campaign is finalizing the **scripts and storyboards** for all 5 videos. David and Frank, please prioritize this to meet the filming schedule.",
    createdAt: "2025-02-20T05:03:28.000Z",
    senderId: "user-11",
    projectId: 58,
    taskId: null,
    parentId: null,
  },
  {
    id: 5148,
    content: "I've drafted 3 concepts focusing on product benefits and engagement. I need Grace's input on which two target audiences to focus on for the remaining scripts.",
    createdAt: "2025-02-21T14:06:59.000Z",
    senderId: "user-14",
    projectId: 58,
    taskId: null,
    parentId: 5147,
  },
  {
    id: 5149,
    content: "The two key target audiences are 'SMB Owners' and 'Remote Employees'. Focus on different pain points for each segment to facilitate effective A/B testing.",
    createdAt: "2025-02-20T13:52:48.000Z",
    senderId: "user-17",
    projectId: 58,
    taskId: null,
    parentId: 5148,
  },
  {
    id: 5150,
    content: "We need clear specifications for video length and aspect ratios for each platform (16:9 for YouTube, 9:16 for TikTok/Reels). Jack, please compile the technical requirements.",
    createdAt: "2025-02-20T03:10:46.000Z",
    senderId: "user-16",
    projectId: 58,
    taskId: null,
    parentId: null,
  },
  {
    id: 5151,
    content: "I'll handle the **final editing and motion graphics**. Bob, please confirm that we have the necessary cloud storage and render farm capacity to manage the 4K video files.",
    createdAt: "2025-02-22T04:45:38.000Z",
    senderId: "user-14",
    projectId: 58,
    taskId: null,
    parentId: null,
  },
  {
    id: 5152,
    content: "Storage capacity is fine on S3, but let's confirm the distribution pipeline for the final assets. Grace, are we using a centralized platform for ad deployment?",
    createdAt: "2025-02-19T06:12:42.000Z",
    senderId: "user-12",
    projectId: 58,
    taskId: null,
    parentId: 5151,
  },
  {
    id: 5153,
    content: "Yes, we are using the internal marketing platform (Project 43 integration) for unified deployment and automated A/B testing tracking.",
    createdAt: "2025-02-21T10:06:50.000Z",
    senderId: "user-17",
    projectId: 58,
    taskId: null,
    parentId: 5152,
  },
  {
    id: 5154,
    content: "Catherine, please develop a QA checklist specifically for video quality (audio sync, artifacting, color grading) before we push to final distribution.",
    createdAt: "2025-02-19T10:02:36.000Z",
    senderId: "user-11",
    projectId: 58,
    taskId: null,
    parentId: null,
  },
  {
    id: 5155,
    content: "The goal is a 20% improvement. Jack, the first step is to establish a performance baseline using profiling tools like **Xcode Instruments and Android Studio Profiler**.",
    createdAt: "2025-02-26T10:00:30.000Z",
    senderId: "user-15",
    projectId: 59,
    taskId: null,
    parentId: null,
  },
  {
    id: 5156,
    content: "I'm setting up automated tests to measure cold boot time and memory consumption for the top five user workflows to create the initial baseline metrics.",
    createdAt: "2025-02-27T05:53:25.000Z",
    senderId: "user-20",
    projectId: 59,
    taskId: null,
    parentId: 5155,
  },
  {
    id: 5157,
    content: "We must identify and fix any **memory leaks**. Bob, are there any known patterns or libraries we need to scrutinize in the codebase?",
    createdAt: "2025-02-27T13:20:38.000Z",
    senderId: "user-13",
    projectId: 59,
    taskId: null,
    parentId: null,
  },
  {
    id: 5158,
    content: "Focus on the image loading library and any large list/feed rendering components. That's where we usually see high memory spikes.",
    createdAt: "2025-02-25T11:26:35.000Z",
    senderId: "user-12",
    projectId: 59,
    taskId: null,
    parentId: 5157,
  },
  {
    id: 5159,
    content: "Battery consumption optimization requires checking background processes and excessive network polling. Alice, what's the desired maximum background synchronization frequency?",
    createdAt: "2025-02-26T12:08:12.000Z",
    senderId: "user-15",
    projectId: 59,
    taskId: null,
    parentId: null,
  },
  {
    id: 5160,
    content: "Background sync should be restricted to once every 30 minutes, or only when the device is charging and on WiFi, unless a high-priority push is received.",
    createdAt: "2025-02-24T05:35:44.000Z",
    senderId: "user-11",
    projectId: 59,
    taskId: null,
    parentId: 5159,
  },
  {
    id: 5161,
    content: "We also need to look at **asset compression**. Frank, can you ensure all static assets (images, icons) are fully optimized for size without sacrificing visual quality?",
    createdAt: "2025-02-25T09:54:00.000Z",
    senderId: "user-14",
    projectId: 59,
    taskId: null,
    parentId: null,
  },
  {
    id: 5162,
    content: "I'll review all image assets and ensure we're using modern formats (WebP/AVIF) and appropriate resolution scaling for different devices to cut down on load times.",
    createdAt: "2025-02-27T10:27:06.000Z",
    senderId: "user-16",
    projectId: 59,
    taskId: null,
    parentId: 5161,
  },
  {
    id: 5163,
    content: "The focus for this project is rapid validation. Frank, what are the three new product features we are prioritizing for the mockups?",
    createdAt: "2025-03-04T05:09:26.000Z",
    senderId: "user-11",
    projectId: 60,
    taskId: null,
    parentId: null,
  },
  {
    id: 5164,
    content: "We are focusing on: 1) AI-powered summary tool, 2) Collaborative document editing, and 3) Enhanced in-app reporting dashboards. I'll start with the user flow mapping for the summary tool.",
    createdAt: "2025-03-02T15:19:10.000Z",
    senderId: "user-16",
    projectId: 60,
    taskId: null,
    parentId: 5163,
  },
  {
    id: 5165,
    content: "David, please ensure the mockups for all three concepts strictly adhere to the updated UI Kit Refresh (Project 54) standards for seamless integration later.",
    createdAt: "2025-03-03T10:46:54.000Z",
    senderId: "user-15",
    projectId: 60,
    taskId: null,
    parentId: null,
  },
  {
    id: 5166,
    content: "I've started the wireframing for the Collaborative Editing feature. We need to define the exact permissions structure for co-editing with the backend team.",
    createdAt: "2025-03-02T10:30:16.000Z",
    senderId: "user-14",
    projectId: 60,
    taskId: null,
    parentId: 5165,
  },
  {
    id: 5167,
    content: "For the Enhanced In-App Reporting, we must incorporate the new data visualization standards established in the Data Analytics Dashboard V2 (Project 47).",
    createdAt: "2025-03-02T15:19:42.000Z",
    senderId: "user-13",
    projectId: 60,
    taskId: null,
    parentId: null,
  },
  {
    id: 5168,
    content: "Bob, Jack, we need your input on the technical feasibility for the AI Summary Tool, specifically how to handle text length limitations and processing time within the prototype.",
    createdAt: "2025-03-04T09:44:15.000Z",
    senderId: "user-16",
    projectId: 60,
    taskId: null,
    parentId: null,
  },
  {
    id: 5169,
    content: "The interactive prototype for the summary tool needs to simulate a realistic, fast response time to ensure a good user experience during testing. No more than 3 seconds perceived latency.",
    createdAt: "2025-03-04T15:30:56.000Z",
    senderId: "user-20",
    projectId: 60,
    taskId: null,
    parentId: 5168,
  },
  {
    id: 5170,
    content: "I'll coordinate the internal stakeholder review session next week. We need to invite Henry and Grace for feedback on the reporting and collaborative features, respectively.",
    createdAt: "2025-03-03T14:00:10.000Z",
    senderId: "user-11",
    projectId: 60,
    taskId: null,
    parentId: null,
  },
  {
    id: 5171,
    content: "I'm setting up the testing environment to capture user interaction data on the prototypes (heatmaps, click paths) during the validation phase.",
    createdAt: "2025-03-02T10:37:44.000Z",
    senderId: "user-17",
    projectId: 60,
    taskId: null,
    parentId: 5170,
  },
];
