export const projects = [
  {
    id: 41,
    title: "E-commerce Platform Redesign",
    description: "Full overhaul of the existing e-commerce platform, focusing on modernizing the UI/UX, improving conversion funnels, and integrating a new payment gateway. The project will involve extensive A/B testing and performance optimization across all major browsers and mobile devices. Key deliverables include a component library and a comprehensive style guide.",
    deadline: "2026-03-30T23:59:59.000Z",
    creatorId: "user-12",
    customerId: 11,
    categoryId: 6,
    statusId: "active",
    createdAt: "2025-01-01T03:00:00.000Z",
  },
  {
    id: 42,
    title: "iOS & Android App Development",
    description: "Design and build a new cross-platform mobile application to complement the company's core services. The app must feature real-time data synchronization, offline capabilities, and push notifications. Technology stack will be React Native to ensure rapid deployment on both iOS and Android platforms. Security audit required prior to launch.",
    deadline: "2026-06-15T23:59:59.000Z",
    creatorId: "user-11",
    customerId: 13,
    categoryId: 7,
    statusId: "pending",
    createdAt: "2025-01-02T10:32:05.000Z",
  },
  {
    id: 43,
    title: "Q4 Digital Marketing Campaign",
    description: "Execute a comprehensive Q4 digital marketing strategy covering SEO content, paid social media ads, and email campaigns. The goal is to increase lead generation by 25% and boost brand awareness in target regions. Requires collaboration with the content and design teams for asset creation and deployment tracking.",
    deadline: "2026-01-31T23:59:59.000Z",
    creatorId: "user-17",
    customerId: 15,
    categoryId: 8,
    statusId: "active",
    createdAt: "2025-01-03T11:59:04.000Z",
  },
  {
    id: 44,
    title: "Internal HR Portal Upgrade",
    description: "Develop and deploy an upgrade for the internal Human Resources portal to include new features like automated time-off requests, performance review tracking, and integration with the existing payroll system. This is a critical internal systems project requiring high attention to data security and compliance standards.",
    deadline: "2026-04-01T23:59:59.000Z",
    creatorId: "user-18",
    customerId: null,
    categoryId: 10,
    statusId: "pending",
    createdAt: "2025-01-05T03:14:13.000Z",
  },
  {
    id: 45,
    title: "Brand Style Guide Finalization",
    description: "Complete the final comprehensive brand style guide, covering typography, color palettes, logo usage, and voice/tone guidelines for all external communication channels. This includes creation of a high-fidelity design system that will be used by both internal and external design partners for future projects and campaigns.",
    deadline: "2026-02-28T23:59:59.000Z",
    creatorId: "user-14",
    customerId: 16,
    categoryId: 9,
    statusId: "completed",
    createdAt: "2025-01-09T14:57:10.000Z",
  },
  {
    id: 46,
    title: "Cloud Infrastructure Migration",
    description: "Migrate the primary application database and associated microservices from the current legacy on-premise servers to a new cloud-based infrastructure (AWS/Azure). The project requires zero downtime during the cutover and a full security audit of the new environment. Comprehensive disaster recovery plans must be documented.",
    deadline: "2026-07-01T23:59:59.000Z",
    creatorId: "user-15",
    customerId: 12,
    categoryId: 6,
    statusId: "active",
    createdAt: "2025-01-13T07:12:28.000Z",
  },
  {
    id: 47,
    title: "Data Analytics Dashboard V2",
    description: "Develop the second version of the internal data analytics dashboard, integrating new data sources from customer interactions and marketing funnels. The V2 dashboard must provide improved visualization, customizable reporting features, and faster query performance for leadership teams and department heads.",
    deadline: "2026-03-05T23:59:59.000Z",
    creatorId: "user-14",
    customerId: 17,
    categoryId: 10,
    statusId: "completed",
    createdAt: "2025-01-18T06:29:49.000Z",
  },
  {
    id: 48,
    title: "Mobile App Feature Expansion",
    description: "Implement three major new features into the existing mobile application: in-app chat support, integrated knowledge base search, and a personalized user feed. Requires updates to the backend API and extensive regression testing to ensure stability of current features on both mobile OS versions.",
    deadline: "2026-05-20T23:59:59.000Z",
    creatorId: "user-20",
    customerId: 14,
    categoryId: 7,
    statusId: "active",
    createdAt: "2025-01-21T08:11:49.000Z",
  },
  {
    id: 49,
    title: "Annual Security Audit",
    description: "Conduct the annual external and internal security audit for all operational systems and codebases. This includes penetration testing, vulnerability scanning, and review of all access control policies. Findings must be documented in a detailed report with clear mitigation steps and a timeline for resolution of critical issues.",
    deadline: "2026-02-15T23:59:59.000Z",
    creatorId: "user-13",
    customerId: 19,
    categoryId: 10,
    statusId: "completed",
    createdAt: "2025-01-22T11:38:53.000Z",
  },
  {
    id: 50,
    title: "New Product Landing Page",
    description: "Design and develop a high-converting landing page for the upcoming product launch. The page must be fully responsive, adhere to the new brand guidelines (Project ID 45), and be optimized for search engine performance. Requires close collaboration between the design, marketing, and front-end development teams for launch coordination.",
    deadline: "2026-04-10T23:59:59.000Z",
    creatorId: "user-16",
    customerId: 20,
    categoryId: 9,
    statusId: "pending",
    createdAt: "2025-01-23T13:41:15.000Z",
  },
  {
    id: 51,
    title: "Supply Chain Optimization App",
    description: "Develop a new mobile application for field agents to track inventory and manage logistics in real-time. The application must integrate with the existing enterprise resource planning (ERP) system and provide geo-location tracking for shipments. Requires robust data validation and offline mode functionality.",
    deadline: "2026-08-01T23:59:59.000Z",
    creatorId: "user-11",
    customerId: 14,
    categoryId: 7,
    statusId: "active",
    createdAt: "2025-01-27T04:52:21.000Z",
  },
  {
    id: 52,
    title: "New Employee Onboarding Flow",
    description: "Re-design the internal new employee onboarding experience, focusing on digital forms, automated task assignment, and integration with the HR portal (Project ID 44). The goal is to reduce manual processing time by 40% and improve the overall new hire satisfaction score. This is an internal efficiency project.",
    deadline: "2026-05-15T23:59:59.000Z",
    creatorId: "user-18",
    customerId: null,
    categoryId: 10,
    statusId: "pending",
    createdAt: "2025-01-31T09:35:22.000Z",
  },
  {
    id: 53,
    title: "SEO Content Strategy Q2",
    description: "Develop and execute the Q2 search engine optimization (SEO) content strategy. This involves keyword research, topic ideation, content creation (articles, guides), and backlink acquisition. The primary metric for success is a 30% increase in organic search traffic and improved keyword rankings for core business terms.",
    deadline: "2026-06-30T23:59:59.000Z",
    creatorId: "user-17",
    customerId: 16,
    categoryId: 8,
    statusId: "active",
    createdAt: "2025-02-01T14:01:55.000Z",
  },
  {
    id: 54,
    title: "UI Kit Refresh & Documentation",
    description: "Update the existing user interface (UI) kit with new components and refine the documentation for consistency across all web and mobile applications. Special focus on accessibility standards (WCAG 2.1) and dark mode implementation. This project is crucial for maintaining design system integrity.",
    deadline: "2026-04-30T23:59:59.000Z",
    creatorId: "user-16",
    customerId: 15,
    categoryId: 9,
    statusId: "completed",
    createdAt: "2025-02-06T09:35:13.000Z",
  },
  {
    id: 55,
    title: "Backend API Restructuring",
    description: "Restructure the core backend application programming interface (API) for improved scalability, faster response times, and better resource utilization. Transition to a microservices architecture where appropriate. Requires careful planning and extensive unit and integration testing to avoid service disruption.",
    deadline: "2026-09-01T23:59:59.000Z",
    creatorId: "user-12",
    customerId: 17,
    categoryId: 6,
    statusId: "active",
    createdAt: "2025-02-11T03:16:42.000Z",
  },
  {
    id: 56,
    title: "Client Feedback Mechanism",
    description: "Implement a new automated client feedback and survey mechanism across various touchpoints (website, application, post-service email). Data collected should automatically feed into the data analytics dashboard (Project ID 47). This requires both front-end widget development and backend data piping.",
    deadline: "2026-05-25T23:59:59.000Z",
    creatorId: "user-13",
    customerId: 11,
    categoryId: 6,
    statusId: "pending",
    createdAt: "2025-02-14T13:00:33.000Z",
  },
  {
    id: 57,
    title: "Annual Financial Reporting System",
    description: "Develop a new automated system for generating annual financial reports compliant with international accounting standards. The system must pull data from multiple existing financial databases and provide audit trails. Requires high security and precision for regulatory purposes.",
    deadline: "2026-01-20T23:59:59.000Z",
    creatorId: "user-19",
    customerId: 20,
    categoryId: 10,
    statusId: "completed",
    createdAt: "2025-02-16T07:39:50.000Z",
  },
  {
    id: 58,
    title: "Video Ad Campaign Production",
    description: "Produce a series of 5 short, high-impact video advertisements for use on social media platforms (YouTube, Instagram, TikTok). This includes scriptwriting, filming, editing, and final distribution coordination with the marketing team. Videos must be A/B tested for optimal click-through rates.",
    deadline: "2026-06-01T23:59:59.000Z",
    creatorId: "user-14",
    customerId: 13,
    categoryId: 8,
    statusId: "active",
    createdAt: "2025-02-19T07:06:28.000Z",
  },
  {
    id: 59,
    title: "Mobile App Performance Tuning",
    description: "Dedicated project to profile and optimize the performance of the core mobile application (iOS/Android). Key areas include reducing load times, minimizing memory usage, and optimizing battery consumption. Target a 20% improvement in perceived performance metrics reported by users.",
    deadline: "2026-07-10T23:59:59.000Z",
    creatorId: "user-20",
    customerId: 12,
    categoryId: 7,
    statusId: "pending",
    createdAt: "2025-02-24T05:04:35.000Z",
  },
  {
    id: 60,
    title: "Product Feature Concept Mockups",
    description: "Create high-fidelity mockups and interactive prototypes for three potential new product features identified during the last planning session. The mockups will be used for internal stakeholder review and initial user testing to validate concepts before full development begins. Requires detailed user flow mapping.",
    deadline: "2026-05-01T23:59:59.000Z",
    creatorId: "user-16",
    customerId: 19,
    categoryId: 9,
    statusId: "pending",
    createdAt: "2025-03-01T14:02:56.000Z",
  },
];
