const prefix = `${process.env.S3_ENDPOINT}/${process.env.S3_BUCKET}/`;

export const taskAttachments = [
  {
    id: 201,
    fileUrl: `${prefix}Task558_TechnicalSpecification.docx`,
    fileName: "Task558_TechnicalSpecification.docx",
    taskId: 558,
    workspaceId: 2,
  },
  {
    id: 424,
    fileUrl: `${prefix}Task558_Summary.docx`,
    fileName: "Task558_Summary.docx",
    taskId: 558,
    workspaceId: 2,
  },
  {
    id: 202,
    fileUrl: `${prefix}Task559_TechnicalSpecification.docx`,
    fileName: "Task559_TechnicalSpecification.docx",
    taskId: 559,
    workspaceId: 2,
  },
  {
    id: 203,
    fileUrl: `${prefix}Task559_Summary.docx`,
    fileName: "Task559_Summary.docx",
    taskId: 559,
    workspaceId: 2,
  },
  {
    id: 204,
    fileUrl: `${prefix}Task560_TechnicalSpecification.docx`,
    fileName: "Task560_TechnicalSpecification.docx",
    taskId: 560,
    workspaceId: 2,
  },
  {
    id: 205,
    fileUrl: `${prefix}Task560_Summary.docx`,
    fileName: "Task560_Summary.docx",
    taskId: 560,
    workspaceId: 2,
  },
  {
    id: 206,
    fileUrl: `${prefix}Task561_TechnicalSpecification.docx`,
    fileName: "Task561_TechnicalSpecification.docx",
    taskId: 561,
    workspaceId: 2,
  },
  {
    id: 207,
    fileUrl: `${prefix}Task561_Summary.docx`,
    fileName: "Task561_Summary.docx",
    taskId: 561,
    workspaceId: 2,
  },
  {
    id: 208,
    fileUrl: `${prefix}Task562_TechnicalSpecification.docx`,
    fileName: "Task562_TechnicalSpecification.docx",
    taskId: 562,
    workspaceId: 2,
  },
  {
    id: 209,
    fileUrl: `${prefix}Task562_Summary.docx`,
    fileName: "Task562_Summary.docx",
    taskId: 562,
    workspaceId: 2,
  },
  {
    id: 210,
    fileUrl: `${prefix}Task563_TechnicalSpecification.docx`,
    fileName: "Task563_TechnicalSpecification.docx",
    taskId: 563,
    workspaceId: 2,
  },
  {
    id: 211,
    fileUrl: `${prefix}Task563_Summary.docx`,
    fileName: "Task563_Summary.docx",
    taskId: 563,
    workspaceId: 2,
  },
  {
    id: 212,
    fileUrl: `${prefix}Task564_TechnicalSpecification.docx`,
    fileName: "Task564_TechnicalSpecification.docx",
    taskId: 564,
    workspaceId: 2,
  },
  {
    id: 213,
    fileUrl: `${prefix}Task564_Summary.docx`,
    fileName: "Task564_Summary.docx",
    taskId: 564,
    workspaceId: 2,
  },
  {
    id: 214,
    fileUrl: `${prefix}Task565_TechnicalSpecification.docx`,
    fileName: "Task565_TechnicalSpecification.docx",
    taskId: 565,
    workspaceId: 2,
  },
  {
    id: 215,
    fileUrl: `${prefix}Task565_Summary.docx`,
    fileName: "Task565_Summary.docx",
    taskId: 565,
    workspaceId: 2,
  },
  {
    id: 216,
    fileUrl: `${prefix}Task566_TechnicalSpecification.docx`,
    fileName: "Task566_TechnicalSpecification.docx",
    taskId: 566,
    workspaceId: 2,
  },
  {
    id: 217,
    fileUrl: `${prefix}Task566_Summary.docx`,
    fileName: "Task566_Summary.docx",
    taskId: 566,
    workspaceId: 2,
  },
  {
    id: 218,
    fileUrl: `${prefix}Task567_TechnicalSpecification.docx`,
    fileName: "Task567_TechnicalSpecification.docx",
    taskId: 567,
    workspaceId: 2,
  },
  {
    id: 219,
    fileUrl: `${prefix}Task567_Summary.docx`,
    fileName: "Task567_Summary.docx",
    taskId: 567,
    workspaceId: 2,
  },
  {
    id: 220,
    fileUrl: `${prefix}Task568_TechnicalSpecification.docx`,
    fileName: "Task568_TechnicalSpecification.docx",
    taskId: 568,
    workspaceId: 2,
  },
  {
    id: 221,
    fileUrl: `${prefix}Task568_Summary.docx`,
    fileName: "Task568_Summary.docx",
    taskId: 568,
    workspaceId: 2,
  },
  {
    id: 222,
    fileUrl: `${prefix}Task569_TechnicalSpecification.docx`,
    fileName: "Task569_TechnicalSpecification.docx",
    taskId: 569,
    workspaceId: 2,
  },
  {
    id: 223,
    fileUrl: `${prefix}Task569_Summary.docx`,
    fileName: "Task569_Summary.docx",
    taskId: 569,
    workspaceId: 2,
  },
  {
    id: 224,
    fileUrl: `${prefix}Task570_TechnicalSpecification.docx`,
    fileName: "Task570_TechnicalSpecification.docx",
    taskId: 570,
    workspaceId: 2,
  },
  {
    id: 225,
    fileUrl: `${prefix}Task570_Summary.docx`,
    fileName: "Task570_Summary.docx",
    taskId: 570,
    workspaceId: 2,
  },
  {
    id: 226,
    fileUrl: `${prefix}Task571_TechnicalSpecification.docx`,
    fileName: "Task571_TechnicalSpecification.docx",
    taskId: 571,
    workspaceId: 2,
  },
  {
    id: 227,
    fileUrl: `${prefix}Task571_Summary.docx`,
    fileName: "Task571_Summary.docx",
    taskId: 571,
    workspaceId: 2,
  },
  {
    id: 228,
    fileUrl: `${prefix}Task572_TechnicalSpecification.docx`,
    fileName: "Task572_TechnicalSpecification.docx",
    taskId: 572,
    workspaceId: 2,
  },
  {
    id: 229,
    fileUrl: `${prefix}Task572_Summary.docx`,
    fileName: "Task572_Summary.docx",
    taskId: 572,
    workspaceId: 2,
  },
  {
    id: 230,
    fileUrl: `${prefix}Task573_TechnicalSpecification.docx`,
    fileName: "Task573_TechnicalSpecification.docx",
    taskId: 573,
    workspaceId: 2,
  },
  {
    id: 231,
    fileUrl: `${prefix}Task573_Summary.docx`,
    fileName: "Task573_Summary.docx",
    taskId: 573,
    workspaceId: 2,
  },
  {
    id: 232,
    fileUrl: `${prefix}Task574_TechnicalSpecification.docx`,
    fileName: "Task574_TechnicalSpecification.docx",
    taskId: 574,
    workspaceId: 2,
  },
  {
    id: 233,
    fileUrl: `${prefix}Task574_Summary.docx`,
    fileName: "Task574_Summary.docx",
    taskId: 574,
    workspaceId: 2,
  },
  {
    id: 234,
    fileUrl: `${prefix}Task575_TechnicalSpecification.docx`,
    fileName: "Task575_TechnicalSpecification.docx",
    taskId: 575,
    workspaceId: 2,
  },
  {
    id: 235,
    fileUrl: `${prefix}Task575_Summary.docx`,
    fileName: "Task575_Summary.docx",
    taskId: 575,
    workspaceId: 2,
  },
  {
    id: 236,
    fileUrl: `${prefix}Task576_TechnicalSpecification.docx`,
    fileName: "Task576_TechnicalSpecification.docx",
    taskId: 576,
    workspaceId: 2,
  },
  {
    id: 237,
    fileUrl: `${prefix}Task576_Summary.docx`,
    fileName: "Task576_Summary.docx",
    taskId: 576,
    workspaceId: 2,
  },
  {
    id: 238,
    fileUrl: `${prefix}Task577_TechnicalSpecification.docx`,
    fileName: "Task577_TechnicalSpecification.docx",
    taskId: 577,
    workspaceId: 2,
  },
  {
    id: 239,
    fileUrl: `${prefix}Task577_Summary.docx`,
    fileName: "Task577_Summary.docx",
    taskId: 577,
    workspaceId: 2,
  },
  {
    id: 240,
    fileUrl: `${prefix}Task578_TechnicalSpecification.docx`,
    fileName: "Task578_TechnicalSpecification.docx",
    taskId: 578,
    workspaceId: 2,
  },
  {
    id: 241,
    fileUrl: `${prefix}Task578_Summary.docx`,
    fileName: "Task578_Summary.docx",
    taskId: 578,
    workspaceId: 2,
  },
];
