const prefix = `${process.env.S3_ENDPOINT}/${process.env.S3_BUCKET}/`;

export const users = [
  {
    id: "user-11",
    fullName: "Alice Johnson",
    bio: "Head of Strategic Initiatives and Project Oversight. Focus on delivery alignment.",
    address: "123 Executive Way, San Francisco, CA 94107",
    birthdate: new Date("1980-05-15"),
    role: "owner",
    email: "alice.johnson@corp.com",
    emailVerified: true,
    imageUrl: `${prefix}user-11.jpg`,
    phoneNumber: "+1-555-123-4567",
    publicLink: null,
    positionId: 6, // Project Manager
    createdAt: new Date("2023-01-10T10:00:00Z"),
    workspaceId: 2,
  },
  {
    id: "user-12",
    fullName: "Bob Smith",
    bio: "Lead Software Engineer specializing in backend infrastructure and scalable cloud services (AWS, Azure).",
    address: "456 Tech Drive, Seattle, WA 98101",
    birthdate: new Date("1992-11-20"),
    role: "user",
    email: "bob.smith@corp.com",
    emailVerified: true,
    imageUrl: `${prefix}user-12.jpg`,
    phoneNumber: "+1-555-987-6543",
    publicLink: null,
    positionId: 8, // Backend Developer (Assumed Backend role based on bio)
    createdAt: new Date("2023-01-10T10:00:00Z"),
    workspaceId: 2,
  },
  {
    id: "user-13",
    fullName: "Catherine Lee",
    bio: "Focus on user acceptance testing, product quality, and agile development methodologies.",
    address: "789 Innovation Lane, New York, NY 10001",
    birthdate: new Date("1985-08-01"),
    role: "user",
    email: "catherine.lee@corp.com",
    emailVerified: true,
    imageUrl: `${prefix}user-13.jpg`,
    phoneNumber: "+1-555-234-5678",
    publicLink: null,
    positionId: 10, // QA Engineer (Assumed QA/Testing role for 'Product Manager' if no PM role available)
    createdAt: new Date("2023-01-10T10:00:00Z"),
    workspaceId: 2,
  },
  {
    id: "user-14",
    fullName: "David Chen",
    bio: "UI/UX Designer and Data Analyst focused on translating business intelligence into user-friendly layouts.",
    address: "101 Analytics Blvd, Austin, TX 73301",
    birthdate: new Date("1995-03-10"),
    role: "user",
    email: "david.chen@corp.com",
    emailVerified: false,
    imageUrl: `${prefix}user-14.jpg`,
    phoneNumber: "+1-555-345-6789",
    publicLink: null,
    positionId: 9, // UI/UX Designer (Best fit for Data Analyst/Designer blend)
    createdAt: new Date("2023-01-10T10:00:00Z"),
    workspaceId: 2,
  },
  {
    id: "user-15",
    fullName: "Emily White",
    bio: "Chief Technology Officer driving the company's technical vision and R&D strategy.",
    address: "202 R&D Center, Boston, MA 02108",
    birthdate: new Date("1978-01-25"),
    role: "manager",
    email: "emily.white@corp.com",
    emailVerified: true,
    imageUrl: `${prefix}user-15.jpg`,
    phoneNumber: "+1-555-456-7890",
    publicLink: null,
    positionId: 8, // Backend Developer (Assumed CTO oversees Backend/Infrastructure)
    createdAt: new Date("2023-01-10T10:00:00Z"),
    workspaceId: 2,
  },
  {
    id: "user-16",
    fullName: "Frank Green",
    bio: "UX/UI Designer specializing in mobile application interfaces and user journey mapping.",
    address: "303 Design Studio, Portland, OR 97204",
    birthdate: new Date("1998-07-04"),
    role: "user",
    email: "frank.green@corp.com",
    emailVerified: true,
    imageUrl: `${prefix}user-16.jpg`,
    phoneNumber: "+1-555-567-8901",
    publicLink: null,
    positionId: 9, // UI/UX Designer
    createdAt: new Date("2023-01-10T10:00:00Z"),
    workspaceId: 2,
  },
  {
    id: "user-17",
    fullName: "Grace Hall",
    bio: "Marketing Specialist focusing on SEO, content creation, and project coordination.",
    address: "404 Marketing Hub, Denver, CO 80202",
    birthdate: new Date("1993-02-28"),
    role: "user",
    email: "grace.hall@corp.com",
    emailVerified: true,
    imageUrl: `${prefix}user-17.jpg`,
    phoneNumber: "+1-555-678-9012",
    publicLink: null,
    positionId: 6, // Project Manager (Assumed PM role for 'Marketing Specialist' to cover cross-functional work)
    createdAt: new Date("2023-01-10T10:00:00Z"),
    workspaceId: 2,
  },
  {
    id: "user-18",
    fullName: "Henry Miller",
    bio: "Project Manager/HR Manager overseeing talent acquisition, employee relations, and compliance.",
    address: "505 HR Tower, Chicago, IL 60601",
    birthdate: new Date("1982-12-07"),
    role: "manager",
    email: "henry.miller@corp.com",
    emailVerified: true,
    imageUrl: `${prefix}user-18.jpg`,
    phoneNumber: "+1-555-789-0123",
    publicLink: null,
    positionId: 6, // Project Manager (Best fit for HR/Admin)
    createdAt: new Date("2023-01-10T10:00:00Z"),
    workspaceId: 2,
  },
  {
    id: "user-19",
    fullName: "Ivy Rodriguez",
    bio: "Financial Accountant responsible for general ledger, audits, and quarterly reporting.",
    address: "606 Finance Building, Miami, FL 33101",
    birthdate: new Date("1989-06-18"),
    role: "user",
    email: "ivy.rodriguez@corp.com",
    emailVerified: false,
    imageUrl: `${prefix}user-19.jpg`,
    phoneNumber: "+1-555-890-1234",
    publicLink: null,
    positionId: 6, // Project Manager (Assumed PM role for admin/finance oversight)
    createdAt: new Date("2023-01-10T10:00:00Z"),
    workspaceId: 2,
  },
  {
    id: "user-20",
    fullName: "Jack Taylor",
    bio: "Junior Software Engineer focused on front-end development using React and TypeScript.",
    address: "707 Developer Hub, San Diego, CA 92101",
    birthdate: new Date("2000-04-05"),
    role: "manager",
    email: "jack.taylor@corp.com",
    emailVerified: true,
    imageUrl: `${prefix}user-20.jpg`,
    phoneNumber: "+1-555-012-3456",
    publicLink: null,
    positionId: 7, // Frontend Developer (Corrected from ID 3)
    createdAt: new Date("2023-01-10T10:00:00Z"),
    workspaceId: 2,
  },
];
