import { UserPreview } from "@/lib/queries/types";

export const usersMock: UserPreview[] = [
  {
    id: "user1",
    name: "John Doe",
    email: "user1@example.com",
    imageUrl: "/man.jpg",
    emailVerified: true,
    phone: "+380990000001",
    createdAt: new Date(),
    updatedAt: new Date(),
    role: "Admin",
    publicLink: "https://example.com/user1",
    positionId: 1,
    position: {
      name: "Developer",
      workspaceId: 1,
    },
  },
  {
    id: "user2",
    name: "Jane Smith",
    email: "user2@example.com",
    imageUrl: "/woman.jpg",
    emailVerified: false,
    phone: "+380990000002",
    createdAt: new Date(),
    updatedAt: new Date(),
    role: "User",
    publicLink: "https://example.com/user2",
    positionId: 2,
    position: {
      name: "Designer",
      workspaceId: 1,
    },
  },
  {
    id: "user3",
    name: "Michael Johnson",
    email: "user3@example.com",
    imageUrl: null,
    emailVerified: true,
    phone: "+380990000003",
    createdAt: new Date(),
    updatedAt: new Date(),
    role: "Manager",
    publicLink: "https://example.com/user3",
    positionId: 3,
    position: {
      name: "Product Manager",
      workspaceId: 1,
    },
  },
  {
    id: "user4",
    name: "Emily Davis",
    email: "user4@example.com",
    imageUrl: null,
    emailVerified: true,
    phone: "+380990000004",
    createdAt: new Date(),
    updatedAt: new Date(),
    role: "User",
    publicLink: "https://example.com/user4",
    positionId: 4,
    position: {
      name: "Product Manager",
      workspaceId: 1,
    },
  },
  {
    id: "user5",
    name: "Daniel Wilson",
    email: "user5@example.com",
    imageUrl: null,
    emailVerified: false,
    phone: "+380990000005",
    createdAt: new Date(),
    updatedAt: new Date(),
    role: "User",
    publicLink: "https://example.com/user5",
    positionId: 5,
    position: {
      name: "Product Manager",
      workspaceId: 1,
    },
  },
  {
    id: "user6",
    name: "Sophia Martinez",
    email: "user6@example.com",
    imageUrl: "/woman.jpg",
    emailVerified: true,
    phone: "+380990000006",
    createdAt: new Date(),
    updatedAt: new Date(),
    role: "Admin",
    publicLink: "https://example.com/user6",
    positionId: 6,
    position: {
      name: "Designer",
      workspaceId: 1,
    },
  },
  {
    id: "user7",
    name: "James Brown",
    email: "user7@example.com",
    imageUrl: "/man.jpg",
    emailVerified: false,
    phone: "+380990000007",
    createdAt: new Date(),
    updatedAt: new Date(),
    role: "Manager",
    publicLink: "https://example.com/user7",
    positionId: 7,
    position: {
      name: "Designer",
      workspaceId: 1,
    },
  },
  {
    id: "user8",
    name: "Olivia Garcia",
    email: "user8@example.com",
    imageUrl: "/woman.jpg",
    emailVerified: true,
    phone: "+380990000008",
    createdAt: new Date(),
    updatedAt: new Date(),
    role: "User",
    publicLink: "https://example.com/user8",
    positionId: 8,
    position: {
      name: "Developer",
      workspaceId: 1,
    },
  },
  {
    id: "user9",
    name: "William Miller",
    email: "user9@example.com",
    imageUrl: "/man.jpg",
    emailVerified: true,
    phone: "+380990000009",
    createdAt: new Date(),
    updatedAt: new Date(),
    role: "User",
    publicLink: "https://example.com/user9",
    positionId: 9,
    position: {
      name: "Developer",
      workspaceId: 1,
    },
  },
  {
    id: "user10",
    name: "Ava Taylor",
    email: "user10@example.com",
    imageUrl: "/woman.jpg",
    emailVerified: false,
    phone: "+380990000010",
    createdAt: new Date(),
    updatedAt: new Date(),
    role: "Manager",
    publicLink: "https://example.com/user10",
    positionId: 10,
    position: {
      name: "Developer",
      workspaceId: 1,
    },
  },
];
