export const customersMock = [
  {
    id: 1,
    fullName: "Alice Johnson",
    bio: "Marketing manager with 10 years of experience.",
    imageUrl: "/woman.jpg",
    email: "alice.johnson@example.com",
    phoneNumber: "+1-202-555-0147",
    publicLink: "https://company.com/customers/alice",
    createdAt: new Date("2024-01-15T10:30:00Z"),
    updatedAt: new Date("2024-06-20T12:45:00Z"),
    companyId: 1,
    company: {
      id: 1,
      name: "TechCorp",
      workspaceId: 1,
    },
    projects: [],
    notificationTargets: [],
  },
  {
    id: 2,
    fullName: "Bob Smith",
    bio: "Software engineer specializing in full-stack development.",
    imageUrl: "/man.jpg",
    email: "bob.smith@example.com",
    phoneNumber: "+1-202-555-0199",
    publicLink: "https://company.com/customers/bob",
    createdAt: new Date("2024-02-10T08:00:00Z"),
    updatedAt: new Date("2024-07-01T09:15:00Z"),
    companyId: 1,
    company: {
      id: 1,
      name: "TechCorp",
      workspaceId: 1,
    },
    projects: [],
    notificationTargets: [],
  },
  {
    id: 3,
    fullName: "Clara Davis",
    bio: "Freelance designer focusing on UX/UI projects.",
    imageUrl: "/woman.jpg",
    email: "clara.davis@example.com",
    phoneNumber: null,
    publicLink: null,
    createdAt: new Date("2024-03-05T14:20:00Z"),
    updatedAt: new Date("2024-07-22T17:40:00Z"),
    companyId: 2,
    company: {
      id: 2,
      name: "DesignStudio",
      workspaceId: 1,
    },
    projects: [],
    notificationTargets: [],
  },
  {
    id: 4,
    fullName: "David Lee",
    bio: null,
    imageUrl: null,
    email: "david.lee@example.com",
    phoneNumber: "+44-7700-900123",
    publicLink: "https://company.com/customers/david",
    createdAt: new Date("2024-04-18T11:00:00Z"),
    updatedAt: new Date("2024-08-01T13:30:00Z"),
    companyId: 2,
    company: {
      id: 2,
      name: "DesignStudio",
      workspaceId: 1,
    },
    projects: [],
    notificationTargets: [],
  },
  {
    id: 5,
    fullName: "Emma Wilson",
    bio: "Entrepreneur in the e-commerce space.",
    imageUrl: "/woman.jpg",
    email: "emma.wilson@example.com",
    phoneNumber: "+1-202-555-0173",
    publicLink: "https://company.com/customers/emma",
    createdAt: new Date("2024-05-12T09:45:00Z"),
    updatedAt: new Date("2024-08-15T10:15:00Z"),
    companyId: 3,
    company: {
      id: 3,
      name: "EcomWorld",
      workspaceId: 1,
    },
    projects: [],
    notificationTargets: [],
  },
];
