import "./globals.css";

import { Suspense } from "react";
import type { Metadata, Viewport } from "next";
import { Nunito_Sans } from "next/font/google";
import {
  AppSidebar,
  AppSidebarBody,
  AppSidebarHeader,
  AppSidebarHeading,
} from "@/components/layout/AppSidebar";
import { AppNavigation } from "@/components/layout/AppNavigation";
import { AppHeader } from "@/components/layout/AppHeader";
import { NotificationPopoverTrigger } from "@/components/notifications/NotificationPopoverTrigger";
import { NotificationOverlayList } from "@/components/notifications/NotificationOverlayList";
import { ViewAllButton } from "@/components/notifications/ViewAllButton";
import { NotificationSheetTrigger } from "@/components/notifications/NotificationSheetTrigger";
import { AppBottomSheetTrigger } from "@/components/layout/AppBottomSheetTrigger";
import { AppSidebarSheetTrigger } from "@/components/layout/AppSidebarSheetTrigger";
import { NotificationOverlayItem } from "@/components/notifications/NotificationOverlayItem";
import { Repeat } from "@/components/common/Repeat";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  interactiveWidget: "resizes-content",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className} antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}

export async function Layout({ children }: { children: React.ReactNode }) {
  const notificationListSkeleton = (
    <Repeat items={7} renderItem={() => <NotificationOverlayItem />} />
  );

  return (
    <div className="flex min-h-screen w-full bg-gray-100 dark:bg-gray-900">
      <AppSidebar className="sticky top-0 z-2 h-screen shrink-0 shadow-lg max-xl:hidden">
        <AppSidebarHeader>
          <AppSidebarHeading />
        </AppSidebarHeader>
        <AppSidebarBody>
          <AppNavigation />
        </AppSidebarBody>
      </AppSidebar>

      <div className="flex w-full flex-col">
        <AppHeader
          title="Dashboard"
          notificationPopoverTrigger={
            <NotificationPopoverTrigger
              notificationList={
                <Suspense fallback={notificationListSkeleton}>
                  <>
                    <NotificationOverlayList />
                    <ViewAllButton />
                  </>
                </Suspense>
              }
            />
          }
          notificationSheetTrigger={
            <NotificationSheetTrigger
              notificationList={
                <Suspense fallback={notificationListSkeleton}>
                  <>
                    <NotificationOverlayList />
                    <ViewAllButton />
                  </>
                </Suspense>
              }
            />
          }
          appBottomSheetTrigger={<AppBottomSheetTrigger />}
          appSidebarSheetTrigger={<AppSidebarSheetTrigger />}
        />
        <main className="flex-1 max-md:p-4 md:p-6">{children}</main>
      </div>
    </div>
  );
}
