import "./globals.css";

import { Suspense } from "react";
import type { Metadata, Viewport } from "next";
import { Nunito_Sans } from "next/font/google";
import {
  AppSidebar,
  AppSidebarBody,
  AppSidebarHeader,
  AppSidebarHeading,
} from "@/components/layout/AppSidebar";
import { AppNavigation } from "@/components/layout/AppNavigation";
import { AppHeader } from "@/components/layout/AppHeader";
import { Notifications } from "@/components/notifications/Notifications";
import { NotificationModalTrigger } from "@/components/notifications/NotificationModalTrigger";
import { AppBottomSheetTrigger } from "@/components/layout/AppBottomSheetTrigger";
import { AppSidebarSheetTrigger } from "@/components/layout/AppSidebarSheetTrigger";
import { NotificationListItem } from "@/components/notifications/NotificationListItem";
import { Repeat } from "@/components/common/Repeat";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  interactiveWidget: "resizes-content",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.className} bg-gray-100 antialiased dark:bg-gray-900`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}

export async function Layout({ children }: { children: React.ReactNode }) {
  const notificationListSkeleton = (
    <Repeat items={7} renderItem={() => <NotificationListItem />} />
  );

  return (
    <div className="flex">
      <AppSidebar className="sticky top-0 z-2 h-screen flex-none shadow-lg max-xl:hidden">
        <AppSidebarHeader>
          <AppSidebarHeading />
        </AppSidebarHeader>
        <AppSidebarBody>
          <AppNavigation />
        </AppSidebarBody>
      </AppSidebar>

      <div className="flex flex-auto flex-col">
        <AppHeader
          title="Dashboard"
          notificationModalTrigger={
            <NotificationModalTrigger
              notifications={
                <Suspense fallback={notificationListSkeleton}>
                  <>
                    <Notifications />
                  </>
                </Suspense>
              }
            />
          }
          appBottomSheetTrigger={<AppBottomSheetTrigger />}
          appSidebarSheetTrigger={<AppSidebarSheetTrigger />}
        />
        <main>{children}</main>
      </div>
    </div>
  );
}
