import "server-only";

import { ProjectPreview } from "../types";

export const getProjects = async (): Promise<ProjectPreview[]> => {
  return [
    {
      id: 1,
      title: "Website Redesign",
      description: "Redesign the company website for better UX",
      creatorId: "user1",
      statusId: 2,
      categoryId: 1,
      customerId: 1,
      createdAt: new Date("2025-01-10"),
      updatedAt: new Date("2025-02-05"),
      deadline: new Date("2025-06-30"),
      creator: { id: "user1", fullName: "Alice Smith", imageUrl: "/woman.jpg" },
      status: {
        id: 2,
        nameEn: "Active",
        nameRu: "Активный",
      },
      category: { id: 1, name: "Design" },
      customer: { id: 1, fullName: "John Doe", company: { name: "Doe Inc." } },
      tasks: [
        { statusId: 1 },
        { statusId: 2 },
        { statusId: 2 },
        { statusId: 3 },
      ],
    },
    {
      id: 2,
      title: "Mobile App Launch",
      description: "Launch the new mobile app for iOS and Android",
      creatorId: "user2",
      statusId: 1,
      categoryId: 2,
      customerId: 2,
      createdAt: new Date("2025-03-01"),
      updatedAt: new Date("2025-03-15"),
      deadline: new Date("2025-08-15"),
      creator: { id: "user2", fullName: "Bob Johnson", imageUrl: "/man.jpg" },
      status: {
        id: 1,
        nameEn: "Pending",
        nameRu: "В ожидании",
      },
      category: { id: 2, name: "Development" },
      customer: {
        id: 2,
        fullName: "Sarah Lee",
        company: { name: "Lee Corp." },
      },
      tasks: [
        { statusId: 1 },
        { statusId: 1 },
        { statusId: 2 },
        { statusId: 3 },
        { statusId: 2 },
      ],
    },
    {
      id: 3,
      title: "Marketing Campaign Q2",
      description: "Plan and execute Q2 marketing campaigns",
      creatorId: "user3",
      statusId: 3,
      categoryId: 3,
      customerId: 3,
      createdAt: new Date("2025-02-10"),
      updatedAt: new Date("2025-04-01"),
      deadline: new Date("2025-05-31"),
      creator: { id: "user3", fullName: "Carol White", imageUrl: "/woman.jpg" },
      status: {
        id: 3,
        nameEn: "Completed",
        nameRu: "Завершён",
      },
      category: { id: 3, name: "Marketing" },
      customer: {
        id: 3,
        fullName: "Mike Brown",
        company: { name: "Brown LLC" },
      },
      tasks: [{ statusId: 3 }, { statusId: 3 }, { statusId: 2 }],
    },
    {
      id: 4,
      title: "Server Migration",
      description: "Migrate servers to new cloud provider",
      creatorId: "user4",
      statusId: 2,
      categoryId: 2,
      customerId: 4,
      createdAt: new Date("2025-01-20"),
      updatedAt: new Date("2025-03-10"),
      deadline: new Date("2025-07-15"),
      creator: { id: "user4", fullName: "David Green", imageUrl: "/man.jpg" },
      status: {
        id: 2,
        nameEn: "Active",
        nameRu: "Активный",
      },
      category: { id: 2, name: "IT" },
      customer: {
        id: 4,
        fullName: "Emma Wilson",
        company: { name: "Wilson Tech" },
      },
      tasks: [
        { statusId: 1 },
        { statusId: 2 },
        { statusId: 2 },
        { statusId: 3 },
        { statusId: 1 },
        { statusId: 2 },
      ],
    },
    {
      id: 5,
      title: "SEO Optimization",
      description: "Improve search engine ranking for main site",
      creatorId: "user5",
      statusId: 1,
      categoryId: 3,
      customerId: 5,
      createdAt: new Date("2025-02-15"),
      updatedAt: new Date("2025-03-05"),
      deadline: new Date("2025-06-01"),
      creator: { id: "user5", fullName: "Eva Black", imageUrl: "/woman.jpg" },
      status: {
        id: 1,
        nameEn: "Pending",
        nameRu: "В ожидании",
      },
      category: { id: 3, name: "Marketing" },
      customer: {
        id: 5,
        fullName: "Tom Harris",
        company: { name: "Harris Co." },
      },
      tasks: [
        { statusId: 1 },
        { statusId: 2 },
        { statusId: 2 },
        { statusId: 2 },
      ],
    },
    {
      id: 6,
      title: "Internal Dashboard",
      description: "Build internal analytics dashboard",
      creatorId: "user6",
      statusId: 2,
      categoryId: 2,
      customerId: 6,
      createdAt: new Date("2025-01-25"),
      updatedAt: new Date("2025-03-20"),
      deadline: new Date("2025-09-01"),
      creator: { id: "user6", fullName: "Frank Moore", imageUrl: "/man.jpg" },
      status: {
        id: 2,
        nameEn: "Active",
        nameRu: "Активный",
      },
      category: { id: 2, name: "Development" },
      customer: {
        id: 6,
        fullName: "Linda King",
        company: { name: "King Enterprises" },
      },
      tasks: [
        { statusId: 1 },
        { statusId: 1 },
        { statusId: 2 },
        { statusId: 3 },
        { statusId: 2 },
        { statusId: 2 },
        { statusId: 1 },
      ],
    },
    {
      id: 7,
      title: "Customer Feedback Collection",
      description: "Collect feedback from customers via surveys",
      creatorId: "user7",
      statusId: 3,
      categoryId: 4,
      customerId: 7,
      createdAt: new Date("2025-01-05"),
      updatedAt: new Date("2025-02-28"),
      deadline: new Date("2025-03-20"),
      creator: { id: "user7", fullName: "Grace Hall", imageUrl: "/woman.jpg" },
      status: {
        id: 3,
        nameEn: "Completed",
        nameRu: "Завершён",
      },
      category: { id: 4, name: "Research" },
      customer: {
        id: 7,
        fullName: "Peter Scott",
        company: { name: "Scott Group" },
      },
      tasks: [
        { statusId: 3 },
        { statusId: 3 },
        { statusId: 2 },
        { statusId: 2 },
      ],
    },
    {
      id: 8,
      title: "Product Photography",
      description: "Take photos of new products for catalog",
      creatorId: "user8",
      statusId: 2,
      categoryId: 1,
      customerId: 8,
      createdAt: new Date("2025-03-10"),
      updatedAt: new Date("2025-03-25"),
      deadline: new Date("2025-07-10"),
      creator: { id: "user8", fullName: "Henry Young", imageUrl: "/man.jpg" },
      status: {
        id: 2,
        nameEn: "Active",
        nameRu: "Активный",
      },
      category: { id: 1, name: "Design" },
      customer: {
        id: 8,
        fullName: "Nancy Allen",
        company: { name: "Allen Studio" },
      },
      tasks: [
        { statusId: 1 },
        { statusId: 2 },
        { statusId: 2 },
        { statusId: 3 },
        { statusId: 3 },
        { statusId: 2 },
      ],
    },
    {
      id: 9,
      title: "Cloud Security Audit",
      description: "Perform security audit for cloud infrastructure",
      creatorId: "user9",
      statusId: 1,
      categoryId: 2,
      customerId: 9,
      createdAt: new Date("2025-02-20"),
      updatedAt: new Date("2025-03-15"),
      deadline: new Date("2025-08-05"),
      creator: { id: "user9", fullName: "Ivy Adams", imageUrl: "/woman.jpg" },
      status: {
        id: 1,
        nameEn: "Pending",
        nameRu: "В ожидании",
      },
      category: { id: 2, name: "IT" },
      customer: {
        id: 9,
        fullName: "George Baker",
        company: { name: "Baker Tech" },
      },
      tasks: [{ statusId: 1 }, { statusId: 2 }, { statusId: 2 }],
    },
    {
      id: 10,
      title: "Annual Report 2025",
      description: "Prepare the annual report for 2025",
      creatorId: "user10",
      statusId: 3,
      categoryId: 5,
      customerId: 10,
      createdAt: new Date("2025-01-15"),
      updatedAt: new Date("2025-04-10"),
      deadline: new Date("2025-05-31"),
      creator: { id: "user10", fullName: "Jack Carter", imageUrl: "/man.jpg" },
      status: {
        id: 3,
        nameEn: "Completed",
        nameRu: "Завершён",
      },
      category: { id: 5, name: "Finance" },
      customer: {
        id: 10,
        fullName: "Olivia Evans",
        company: { name: "Evans Ltd." },
      },
      tasks: [
        { statusId: 3 },
        { statusId: 3 },
        { statusId: 2 },
        { statusId: 2 },
        { statusId: 3 },
        { statusId: 2 },
        { statusId: 1 },
        { statusId: 2 },
      ],
    },
  ];
};

export const getTotalProjects = async () => {
  return 100;
};

export const getProjectCategories = async () => {
  return [
    {
      id: 1,
      name: "Design & UX",
      workspaceId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      name: "Development & Engineering",
      workspaceId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 3,
      name: "Marketing & Strategy",
      workspaceId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 4,
      name: "Data & Analytics",
      workspaceId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 5,
      name: "SEO Optimization",
      workspaceId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
};
