import "../globals.css";

import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { SWRProvider } from "./SWRProvider";
import type { Metadata, Viewport } from "next";
import { Nunito_Sans } from "next/font/google";
import { I18nProvider } from "@/components/ui/I18nProvider";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { RouterProvider } from "@/components/ui/RouterProvider";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  interactiveWidget: "resizes-content",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang="en">
      <body
        className={`${nunitoSans.className} bg-gray-100 antialiased dark:bg-gray-900`}
      >
        <SWRProvider>
          <NextIntlClientProvider>
            <I18nProvider locale={locale}>
              <RouterProvider>{children}</RouterProvider>
            </I18nProvider>
          </NextIntlClientProvider>
        </SWRProvider>
      </body>
    </html>
  );
}
