import { ProjectPreview } from "@/lib/queries/types";
import {
  ACTIVE_PROJECT_STATUS_ID,
  COMPLETED_PROJECT_STATUS_ID,
  PENDING_PROJECT_STATUS_ID,
} from "@/lib/queries/constants";

export const projectsMock: ProjectPreview[] = [
  {
    id: 1,
    title: "Website Redesign",
    description: "Redesign the company website for better UX",
    creatorId: "user1",
    statusId: ACTIVE_PROJECT_STATUS_ID,
    categoryId: 1,
    customerId: 1,
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-02-05"),
    deadline: new Date("2025-06-30"),
    creator: { name: "Alice Smith", imageUrl: "/woman.jpg" },
    status: {
      id: ACTIVE_PROJECT_STATUS_ID,
      nameEn: "Active",
      nameRu: "Активный",
    },
    category: { name: "Design" },
    customer: { fullName: "John Doe", company: { name: "Doe Inc." } },
    tasks: [{ statusId: 1 }, { statusId: 2 }, { statusId: 2 }, { statusId: 3 }],
  },
  {
    id: 2,
    title: "Mobile App Launch",
    description: "Launch the new mobile app for iOS and Android",
    creatorId: "user2",
    statusId: PENDING_PROJECT_STATUS_ID,
    categoryId: 2,
    customerId: 2,
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-15"),
    deadline: new Date("2025-08-15"),
    creator: { name: "Bob Johnson", imageUrl: "/man.jpg" },
    status: {
      id: PENDING_PROJECT_STATUS_ID,
      nameEn: "Pending",
      nameRu: "В ожидании",
    },
    category: { name: "Development" },
    customer: { fullName: "Sarah Lee", company: { name: "Lee Corp." } },
    tasks: [
      { statusId: 1 },
      { statusId: 1 },
      { statusId: 2 },
      { statusId: 3 },
      { statusId: 2 },
    ],
  },
  {
    id: 3,
    title: "Marketing Campaign Q2",
    description: "Plan and execute Q2 marketing campaigns",
    creatorId: "user3",
    statusId: COMPLETED_PROJECT_STATUS_ID,
    categoryId: 3,
    customerId: 3,
    createdAt: new Date("2025-02-10"),
    updatedAt: new Date("2025-04-01"),
    deadline: new Date("2025-05-31"),
    creator: { name: "Carol White", imageUrl: "/woman.jpg" },
    status: {
      id: COMPLETED_PROJECT_STATUS_ID,
      nameEn: "Completed",
      nameRu: "Завершён",
    },
    category: { name: "Marketing" },
    customer: { fullName: "Mike Brown", company: { name: "Brown LLC" } },
    tasks: [{ statusId: 3 }, { statusId: 3 }, { statusId: 2 }],
  },
  {
    id: 4,
    title: "Server Migration",
    description: "Migrate servers to new cloud provider",
    creatorId: "user4",
    statusId: ACTIVE_PROJECT_STATUS_ID,
    categoryId: 2,
    customerId: 4,
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-03-10"),
    deadline: new Date("2025-07-15"),
    creator: { name: "David Green", imageUrl: "/man.jpg" },
    status: {
      id: ACTIVE_PROJECT_STATUS_ID,
      nameEn: "Active",
      nameRu: "Активный",
    },
    category: { name: "IT" },
    customer: { fullName: "Emma Wilson", company: { name: "Wilson Tech" } },
    tasks: [
      { statusId: 1 },
      { statusId: 2 },
      { statusId: 2 },
      { statusId: 3 },
      { statusId: 1 },
      { statusId: 2 },
    ],
  },
  {
    id: 5,
    title: "SEO Optimization",
    description: "Improve search engine ranking for main site",
    creatorId: "user5",
    statusId: PENDING_PROJECT_STATUS_ID,
    categoryId: 3,
    customerId: 5,
    createdAt: new Date("2025-02-15"),
    updatedAt: new Date("2025-03-05"),
    deadline: new Date("2025-06-01"),
    creator: { name: "Eva Black", imageUrl: "/woman.jpg" },
    status: {
      id: PENDING_PROJECT_STATUS_ID,
      nameEn: "Pending",
      nameRu: "В ожидании",
    },
    category: { name: "Marketing" },
    customer: { fullName: "Tom Harris", company: { name: "Harris Co." } },
    tasks: [{ statusId: 1 }, { statusId: 2 }, { statusId: 2 }, { statusId: 2 }],
  },
  {
    id: 6,
    title: "Internal Dashboard",
    description: "Build internal analytics dashboard",
    creatorId: "user6",
    statusId: ACTIVE_PROJECT_STATUS_ID,
    categoryId: 2,
    customerId: 6,
    createdAt: new Date("2025-01-25"),
    updatedAt: new Date("2025-03-20"),
    deadline: new Date("2025-09-01"),
    creator: { name: "Frank Moore", imageUrl: "/man.jpg" },
    status: {
      id: ACTIVE_PROJECT_STATUS_ID,
      nameEn: "Active",
      nameRu: "Активный",
    },
    category: { name: "Development" },
    customer: { fullName: "Linda King", company: { name: "King Enterprises" } },
    tasks: [
      { statusId: 1 },
      { statusId: 1 },
      { statusId: 2 },
      { statusId: 3 },
      { statusId: 2 },
      { statusId: 2 },
      { statusId: 1 },
    ],
  },
  {
    id: 7,
    title: "Customer Feedback Collection",
    description: "Collect feedback from customers via surveys",
    creatorId: "user7",
    statusId: COMPLETED_PROJECT_STATUS_ID,
    categoryId: 4,
    customerId: 7,
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-02-28"),
    deadline: new Date("2025-03-20"),
    creator: { name: "Grace Hall", imageUrl: "/woman.jpg" },
    status: {
      id: COMPLETED_PROJECT_STATUS_ID,
      nameEn: "Completed",
      nameRu: "Завершён",
    },
    category: { name: "Research" },
    customer: { fullName: "Peter Scott", company: { name: "Scott Group" } },
    tasks: [{ statusId: 3 }, { statusId: 3 }, { statusId: 2 }, { statusId: 2 }],
  },
  {
    id: 8,
    title: "Product Photography",
    description: "Take photos of new products for catalog",
    creatorId: "user8",
    statusId: ACTIVE_PROJECT_STATUS_ID,
    categoryId: 1,
    customerId: 8,
    createdAt: new Date("2025-03-10"),
    updatedAt: new Date("2025-03-25"),
    deadline: new Date("2025-07-10"),
    creator: { name: "Henry Young", imageUrl: "/man.jpg" },
    status: {
      id: ACTIVE_PROJECT_STATUS_ID,
      nameEn: "Active",
      nameRu: "Активный",
    },
    category: { name: "Design" },
    customer: { fullName: "Nancy Allen", company: { name: "Allen Studio" } },
    tasks: [
      { statusId: 1 },
      { statusId: 2 },
      { statusId: 2 },
      { statusId: 3 },
      { statusId: 3 },
      { statusId: 2 },
    ],
  },
  {
    id: 9,
    title: "Cloud Security Audit",
    description: "Perform security audit for cloud infrastructure",
    creatorId: "user9",
    statusId: PENDING_PROJECT_STATUS_ID,
    categoryId: 2,
    customerId: 9,
    createdAt: new Date("2025-02-20"),
    updatedAt: new Date("2025-03-15"),
    deadline: new Date("2025-08-05"),
    creator: { name: "Ivy Adams", imageUrl: "/woman.jpg" },
    status: {
      id: PENDING_PROJECT_STATUS_ID,
      nameEn: "Pending",
      nameRu: "В ожидании",
    },
    category: { name: "IT" },
    customer: { fullName: "George Baker", company: { name: "Baker Tech" } },
    tasks: [{ statusId: 1 }, { statusId: 2 }, { statusId: 2 }],
  },
  {
    id: 10,
    title: "Annual Report 2025",
    description: "Prepare the annual report for 2025",
    creatorId: "user10",
    statusId: COMPLETED_PROJECT_STATUS_ID,
    categoryId: 5,
    customerId: 10,
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-04-10"),
    deadline: new Date("2025-05-31"),
    creator: { name: "Jack Carter", imageUrl: "/man.jpg" },
    status: {
      id: COMPLETED_PROJECT_STATUS_ID,
      nameEn: "Completed",
      nameRu: "Завершён",
    },
    category: { name: "Finance" },
    customer: { fullName: "Olivia Evans", company: { name: "Evans Ltd." } },
    tasks: [
      { statusId: 3 },
      { statusId: 3 },
      { statusId: 2 },
      { statusId: 2 },
      { statusId: 3 },
      { statusId: 2 },
      { statusId: 1 },
      { statusId: 2 },
    ],
  },
];
