import { TaskCommentPreview } from "@/lib/queries/types";

export const mockedTaskComments: TaskCommentPreview[] = [
  {
    id: 1,
    content: "Please review the latest homepage design.",
    taskId: 101,
    senderId: "u1",
    sender: {
      name: "Alice Johnson",
      imageUrl: "/woman.jpg",
    },
    task: { title: "Design homepage layout" },
    createdAt: new Date("2025-09-20T08:00:00Z"),
    updatedAt: new Date("2025-09-20T08:05:00Z"),
  },
  {
    id: 2,
    content: "Fixed the bug in the login flow.",
    taskId: 102,
    senderId: "u2",
    sender: { name: "Bob Smith", imageUrl: "/man.jpg" },
    task: { title: "Fix login bug" },
    createdAt: new Date("2025-09-20T09:15:00Z"),
    updatedAt: new Date("2025-09-20T09:20:00Z"),
  },
  {
    id: 3,
    content: "Updated API documentation as requested.",
    taskId: 103,
    senderId: "u3",
    sender: {
      name: "Charlie Davis",
      imageUrl: "/man.jpg",
    },
    task: { title: "Update API docs" },
    createdAt: new Date("2025-09-19T12:30:00Z"),
    updatedAt: new Date("2025-09-19T12:35:00Z"),
  },
  {
    id: 4,
    content: "Added unit tests for the new feature.",
    taskId: 104,
    senderId: "u4",
    sender: { name: "Diana Lee", imageUrl: "/woman.jpg" },
    task: { title: "Add unit tests" },
    createdAt: new Date("2025-09-19T14:00:00Z"),
    updatedAt: new Date("2025-09-19T14:05:00Z"),
  },
  {
    id: 5,
    content: "Please check the styling on mobile devices.",
    taskId: 105,
    senderId: "u5",
    sender: { name: "Ethan Wright", imageUrl: "/man.jpg" },
    task: { title: "Responsive design review" },
    createdAt: new Date("2025-09-18T11:45:00Z"),
    updatedAt: new Date("2025-09-18T11:50:00Z"),
  },
  {
    id: 6,
    content: "Refactored the component for better readability.",
    taskId: 106,
    senderId: "u6",
    sender: { name: "Fiona Green", imageUrl: "/woman.jpg" },
    task: { title: "Refactor dashboard component" },
    createdAt: new Date("2025-09-18T13:20:00Z"),
    updatedAt: new Date("2025-09-18T13:25:00Z"),
  },
  {
    id: 7,
    content: "Updated dependencies to the latest versions.",
    taskId: 107,
    senderId: "u7",
    sender: {
      name: "George Brown",
      imageUrl: "/man.jpg",
    },
    task: { title: "Update project dependencies" },
    createdAt: new Date("2025-09-17T15:00:00Z"),
    updatedAt: new Date("2025-09-17T15:05:00Z"),
  },
  {
    id: 8,
    content: "Added error handling to the API routes.",
    taskId: 108,
    senderId: "u8",
    sender: { name: "Hannah White", imageUrl: "/man.jpg" },
    task: { title: "Improve API error handling" },
    createdAt: new Date("2025-09-17T16:30:00Z"),
    updatedAt: new Date("2025-09-17T16:35:00Z"),
  },
  {
    id: 9,
    content: "Optimized images for faster loading.",
    taskId: 109,
    senderId: "u9",
    sender: { name: "Ian Black", imageUrl: "/man.jpg" },
    task: { title: "Optimize images" },
    createdAt: new Date("2025-09-16T10:10:00Z"),
    updatedAt: new Date("2025-09-16T10:15:00Z"),
  },
  {
    id: 10,
    content:
      "I have thoroughly reviewed pull request #42 and carefully examined all the changes submitted. After verifying that the code aligns with our project standards.",
    taskId: 110,
    senderId: "u10",
    sender: { name: "Julia King", imageUrl: "/woman.jpg" },
    task: { title: "Review pull request #42" },
    createdAt: new Date("2025-09-16T11:50:00Z"),
    updatedAt: new Date("2025-09-16T11:55:00Z"),
  },
];
