import { TaskPreview } from "@/lib/queries/types";
import {
  ACTIVE_TASK_STATUS_ID,
  DONE_TASK_STATUS_ID,
  PENDING_TASK_STATUS_ID,
} from "@/lib/queries/constants";

export const tasksMock: TaskPreview[] = [
  {
    id: 1,
    title: "Design landing page",
    description: "Create the main landing page UI",
    deadline: new Date("2025-09-30"),
    projectId: 1,
    creatorId: "user1",
    categoryId: 1,
    statusId: PENDING_TASK_STATUS_ID,
    createdAt: new Date("2025-09-01"),
    updatedAt: new Date("2025-09-15"),

    creator: { imageUrl: "/man.jpg", name: "John Doe" },
    status: {
      id: PENDING_TASK_STATUS_ID,
      nameEn: "Pending",
      nameRu: "Ожидает",
    },
    category: { name: "Design" },
    subtasks: [
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: false },
      { isDone: false },
      { isDone: true },
    ],
  },
  {
    id: 2,
    title: "Implement login system",
    description: "Add email and password login with validation",
    deadline: new Date("2025-10-05"),
    projectId: 1,
    creatorId: "user2",
    categoryId: 2,
    statusId: ACTIVE_TASK_STATUS_ID,
    createdAt: new Date("2025-09-02"),
    updatedAt: new Date("2025-09-16"),

    creator: null,
    status: {
      id: ACTIVE_TASK_STATUS_ID,
      nameEn: "Active",
      nameRu: "Активно",
    },
    category: { name: "Development" },
    subtasks: [
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: false },
      { isDone: true },
    ],
  },
  {
    id: 3,
    title: "Database schema migration",
    description: "Prepare migration scripts for PostgreSQL",
    deadline: new Date("2025-10-10"),
    projectId: 2,
    creatorId: "user3",
    categoryId: 3,
    statusId: DONE_TASK_STATUS_ID,
    createdAt: new Date("2025-09-03"),
    updatedAt: new Date("2025-09-17"),

    creator: { imageUrl: null, name: "Jane Doe" },
    status: {
      id: DONE_TASK_STATUS_ID,
      nameEn: "Done",
      nameRu: "Выполнено",
    },
    category: { name: "Backend" },
    subtasks: [
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: true },
    ],
  },
  {
    id: 4,
    title: "Write unit tests",
    description: "Ensure code coverage for critical modules",
    deadline: new Date("2025-10-12"),
    projectId: 2,
    creatorId: "user4",
    categoryId: 4,
    statusId: PENDING_TASK_STATUS_ID,
    createdAt: new Date("2025-09-04"),
    updatedAt: new Date("2025-09-17"),

    creator: { imageUrl: "/man.jpg", name: "John Doe" },
    status: {
      id: PENDING_TASK_STATUS_ID,
      nameEn: "Pending",
      nameRu: "Ожидает",
    },
    category: { name: "Testing" },
    subtasks: [
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: false },
      { isDone: false },
      { isDone: false },
      { isDone: false },
      { isDone: true },
    ],
  },
  {
    id: 5,
    title: "Prepare deployment pipeline",
    description: "Set up CI/CD with GitHub Actions",
    deadline: new Date("2025-10-15"),
    projectId: 2,
    creatorId: "user5",
    categoryId: 5,
    statusId: ACTIVE_TASK_STATUS_ID,
    createdAt: new Date("2025-09-05"),
    updatedAt: new Date("2025-09-18"),

    creator: { imageUrl: "/man.jpg", name: "John Doe" },
    status: {
      id: ACTIVE_TASK_STATUS_ID,
      nameEn: "Active",
      nameRu: "Активно",
    },
    category: { name: "DevOps" },
    subtasks: [
      { isDone: false },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: false },
      { isDone: false },
      { isDone: false },
      { isDone: false },
      { isDone: true },
    ],
  },
  {
    id: 6,
    title: "Set up staging environment",
    description: "Deploy staging server for testing",
    deadline: new Date("2025-10-18"),
    projectId: 2,
    creatorId: "user6",
    categoryId: 6,
    statusId: DONE_TASK_STATUS_ID,
    createdAt: new Date("2025-09-06"),
    updatedAt: new Date("2025-09-18"),

    creator: { imageUrl: "/man.jpg", name: "John Doe" },
    status: {
      id: DONE_TASK_STATUS_ID,
      nameEn: "Done",
      nameRu: "Выполнено",
    },
    category: { name: "Infrastructure" },
    subtasks: [
      { isDone: false },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
    ],
  },
  {
    id: 7,
    title: "Create onboarding flow",
    description: "Implement user onboarding screens",
    deadline: new Date("2025-10-20"),
    projectId: 3,
    creatorId: "user7",
    categoryId: 7,
    statusId: DONE_TASK_STATUS_ID,
    createdAt: new Date("2025-09-07"),
    updatedAt: new Date("2025-09-19"),

    creator: { imageUrl: "/man.jpg", name: "John Doe" },
    status: {
      id: DONE_TASK_STATUS_ID,
      nameEn: "Done",
      nameRu: "Выполнено",
    },
    category: { name: "UX" },
    subtasks: [
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
    ],
  },
  {
    id: 8,
    title: "Fix payment bug",
    description: "Resolve payment gateway error on checkout",
    deadline: new Date("2025-10-22"),
    projectId: 3,
    creatorId: "user8",
    categoryId: 8,
    statusId: ACTIVE_TASK_STATUS_ID,
    createdAt: new Date("2025-09-08"),
    updatedAt: new Date("2025-09-19"),

    creator: { imageUrl: "/man.jpg", name: "John Doe" },
    status: {
      id: ACTIVE_TASK_STATUS_ID,
      nameEn: "Active",
      nameRu: "Активно",
    },
    category: { name: "Bugfix" },
    subtasks: [
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: false },
      { isDone: false },
    ],
  },
  {
    id: 9,
    title: "Optimize image loading",
    description: "Use lazy-loading and compression",
    deadline: new Date("2025-10-25"),
    projectId: 3,
    creatorId: "user9",
    categoryId: 9,
    statusId: PENDING_TASK_STATUS_ID,
    createdAt: new Date("2025-09-09"),
    updatedAt: new Date("2025-09-19"),

    creator: { imageUrl: null, name: "Jane Doe" },
    status: {
      id: PENDING_TASK_STATUS_ID,
      nameEn: "Pending",
      nameRu: "Ожидает",
    },
    category: { name: "Performance" },
    subtasks: [
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: false },
    ],
  },
  {
    id: 10,
    title: "Refactor auth middleware",
    description: "Simplify authentication logic",
    deadline: new Date("2025-10-28"),
    projectId: 3,
    creatorId: "user10",
    categoryId: 3,
    statusId: DONE_TASK_STATUS_ID,
    createdAt: new Date("2025-09-10"),
    updatedAt: new Date("2025-09-20"),

    creator: null,
    status: {
      id: DONE_TASK_STATUS_ID,
      nameEn: "Done",
      nameRu: "Выполнено",
    },
    category: { name: "Backend" },
    subtasks: [
      { isDone: false },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: true },
      { isDone: false },
      { isDone: false },
      { isDone: false },
      { isDone: false },
      { isDone: true },
      { isDone: true },
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: true },
      { isDone: false },
      { isDone: false },
      { isDone: false },
      { isDone: false },
      { isDone: false },
      { isDone: true },
    ],
  },
];
