import { withBackgroundVariant } from "@/.storybook/decorators";
import { TaskList } from "./TaskList";
import { Meta, StoryObj } from "@storybook/nextjs-vite";

const meta = {
  title: "Components/tasks/TaskList",
  component: TaskList,
  tags: ["autodocs"],
  decorators: [withBackgroundVariant()],
} satisfies Meta<typeof TaskList>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default = {
  args: {
    tasks: [
      {
        id: 1,
        title: "Design landing page",
        deadline: new Date("2025-09-30"),
        project: { title: "Website Redesign", id: 1 },
        creator: { id: "user1", imageUrl: "/man.jpg", fullName: "John Doe" },
        status: {
          id: 1,
          nameEn: "Pending",
          nameRu: "Ожидает",
        },
        category: { id: 1, name: "Design" },
        subtasks: [
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: false },
          { isDone: false },
          { isDone: true },
        ],
        _count: { comments: 10, subtasks: 6 },
      },
      {
        id: 2,
        title: "Implement login system",
        deadline: new Date("2025-10-05"),
        project: { title: "Authentication Module", id: 2 },
        creator: undefined,
        status: {
          id: 2,
          nameEn: "Active",
          nameRu: "Активно",
        },
        category: { id: 2, name: "Development" },
        subtasks: [
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: false },
          { isDone: true },
        ],
        _count: { comments: 22, subtasks: 16 },
      },
      {
        id: 3,
        title: "Database schema migration",
        deadline: new Date("2025-10-10"),
        project: { title: "Core Database Upgrade", id: 3 },
        creator: { id: "user3", imageUrl: undefined, fullName: "Jane Doe" },
        status: {
          id: 3,
          nameEn: "Done",
          nameRu: "Выполнено",
        },
        category: { id: 3, name: "Backend" },
        subtasks: [
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: true },
        ],
        _count: { comments: 2, subtasks: 2 },
      },
      {
        id: 4,
        title: "Write unit tests",
        deadline: new Date("2025-10-12"),
        project: { title: "Quality Assurance Suite", id: 4 },
        creator: { id: "user4", imageUrl: "/man.jpg", fullName: "John Doe" },
        status: {
          id: 1,
          nameEn: "Pending",
          nameRu: "Ожидает",
        },
        category: { id: 4, name: "Testing" },
        subtasks: [
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: false },
          { isDone: false },
          { isDone: false },
          { isDone: false },
          { isDone: true },
        ],
        _count: { comments: 12, subtasks: 32 },
      },
      {
        id: 5,
        title: "Prepare deployment pipeline",
        deadline: new Date("2025-10-15"),
        project: { title: "CI/CD Automation", id: 5 },
        creator: { id: "user5", imageUrl: "/man.jpg", fullName: "John Doe" },
        status: {
          id: 2,
          nameEn: "Active",
          nameRu: "Активно",
        },
        category: { id: 5, name: "DevOps" },
        subtasks: [
          { isDone: false },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: false },
          { isDone: false },
          { isDone: false },
          { isDone: false },
          { isDone: true },
        ],
        _count: { comments: 15, subtasks: 8 },
      },
      {
        id: 6,
        title: "Set up staging environment",
        deadline: new Date("2025-10-18"),
        project: { title: "Infrastructure Setup", id: 6 },
        creator: { id: "user6", imageUrl: "/man.jpg", fullName: "John Doe" },
        status: {
          id: 3,
          nameEn: "Done",
          nameRu: "Выполнено",
        },
        category: { id: 6, name: "Infrastructure" },
        subtasks: [
          { isDone: false },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
        ],
        _count: { comments: 9, subtasks: 16 },
      },
      {
        id: 7,
        title: "Create onboarding flow",
        deadline: new Date("2025-10-20"),
        project: { title: "User Experience Improvements", id: 7 },
        creator: { id: "user7", imageUrl: "/man.jpg", fullName: "John Doe" },
        status: {
          id: 3,
          nameEn: "Done",
          nameRu: "Выполнено",
        },
        category: { id: 7, name: "UX" },
        subtasks: [
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
        ],
        _count: { comments: 12, subtasks: 22 },
      },
      {
        id: 8,
        title: "Fix payment bug",
        deadline: new Date("2025-10-22"),
        project: { title: "E-commerce Platform", id: 8 },
        creator: { id: "user8", imageUrl: "/man.jpg", fullName: "John Doe" },
        status: {
          id: 2,
          nameEn: "Active",
          nameRu: "Активно",
        },
        category: { id: 8, name: "Bugfix" },
        subtasks: [
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: false },
          { isDone: false },
        ],
        _count: { comments: 10, subtasks: 6 },
      },
      {
        id: 9,
        title: "Optimize image loading",
        deadline: new Date("2025-10-25"),
        project: { title: "Performance Optimization", id: 9 },
        creator: { id: "user9", imageUrl: undefined, fullName: "Jane Doe" },
        status: {
          id: 1,
          nameEn: "Pending",
          nameRu: "Ожидает",
        },
        category: { id: 9, name: "Performance" },
        subtasks: [
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: false },
        ],
        _count: { comments: 23, subtasks: 12 },
      },
      {
        id: 10,
        title: "Refactor auth middleware",
        deadline: new Date("2025-10-28"),
        project: { title: "Backend Refactoring", id: 10 },
        creator: undefined,
        status: {
          id: 3,
          nameEn: "Done",
          nameRu: "Выполнено",
        },
        category: { id: 3, name: "Backend" },
        subtasks: [
          { isDone: false },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: true },
          { isDone: false },
          { isDone: false },
          { isDone: false },
          { isDone: false },
          { isDone: true },
          { isDone: true },
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: true },
          { isDone: false },
          { isDone: false },
          { isDone: false },
          { isDone: false },
          { isDone: false },
          { isDone: true },
        ],
        _count: { comments: 13, subtasks: 23 },
      },
    ],
  },
} satisfies Story;
