import { NotificationType, ProjectStatus, TaskStatus } from "@/generated/prisma/client";

export const notifications = [
  //Projects
  {
    id: 1,
    workspaceId: 1,
    actorId: "user-1",
    recipientId: "user-10",
    projectId: 1,
    projectTitle: "Разработка корпоративного сайта",
    type: NotificationType.projectAdded,
    createdAt: "2025-01-01T00:00:00.000Z",
    isRead: true,
  },
  {
    id: 2,
    workspaceId: 1,
    actorId: "user-5",
    recipientId: "user-10",
    projectId: 2,
    projectTitle: "Мобильное приложение (MVP)",
    type: NotificationType.projectChanged,
    createdAt: "2025-01-07T00:00:00.000Z",
    isRead: true,
  },
  {
    id: 3,
    workspaceId: 1,
    actorId: "user-1",
    recipientId: "user-10",
    projectId: 3,
    projectTitle: "Редизайн логотипа и стиля",
    type: NotificationType.projectChanged,
    createdAt: "2025-01-07T00:00:00.000Z",
    isRead: true,
  },
  {
    id: 4,
    workspaceId: 1,
    actorId: "user-5",
    recipientId: "user-10",
    projectTitle: "Разработка сайта для внутреннего использования.",
    type: NotificationType.projectDeleted,
    createdAt: "2025-03-08T00:00:00.000Z",
    isRead: true,
  },

  //Tasks
  {
    id: 5,
    workspaceId: 1,
    actorId: "user-1",
    recipientId: "user-10",
    taskId: 1,
    taskTitle: "Разработка главной страницы (макет)",
    type: NotificationType.taskAdded,
    createdAt: "2025-01-02T00:00:00.000Z",
    isRead: true,
  },
  {
    id: 6,
    workspaceId: 1,
    actorId: "user-5",
    recipientId: "user-10",
    taskId: 2,
    taskTitle: "Мобильное приложение (MVP)",
    type: NotificationType.taskChanged,
    createdAt: "2025-01-06T00:00:00.000Z",
    isRead: true,
  },
  {
    id: 7,
    workspaceId: 1,
    actorId: "user-1",
    recipientId: "user-10",
    taskId: 3,
    taskTitle: "Создание API: список услуг",
    type: NotificationType.taskChanged,
    createdAt: "2025-01-06T00:00:00.000Z",
    isRead: true,
  },
  {
    id: 8,
    workspaceId: 1,
    actorId: "user-5",
    recipientId: "user-10",
    taskTitle: "Проектирование схемы БД.",
    type: NotificationType.taskDeleted,
    createdAt: "2025-03-18T00:00:00.000Z",
    isRead: true,
  },

  //Comments
  {
    id: 9,
    workspaceId: 1,
    actorId: "user-1",
    recipientId: "user-10",
    commentId: 461,
    commentContent: 'Ссылка на облако с контентом отправлена. Все файлы в папке "About_Us_Content". Просьба проверить разрешение перед загрузкой.',
    taskId: 7,
    taskTitle: "Наполнение раздела 'О нас'",
    type: NotificationType.commentAdded,
    createdAt: "2025-01-02T00:00:00.000Z",
    isRead: true,
  },
  {
    id: 10,
    workspaceId: 1,
    actorId: "user-5",
    recipientId: "user-10",
    commentId: 460,
    commentContent: "Какие именно фотографии и логотипы нужно загрузить? Есть ли ссылка на папку с исходниками?",
    taskId: 7,
    taskTitle: "Наполнение раздела 'О нас'",
    type: NotificationType.commentChanged,
    createdAt: "2025-01-06T00:00:00.000Z",
    isRead: true,
  },
  {
    id: 11,
    workspaceId: 1,
    actorId: "user-5",
    recipientId: "user-10",
    commentContent: "Нужен список секций главной страницы, чтобы начать работу над структурой в Figma. Он уже есть или нужны референсы?",
    taskId: 3,
    taskTitle: "Создание API: список услуг",
    type: NotificationType.commentDeleted,
    createdAt: "2025-03-18T00:00:00.000Z",
    isRead: true,
  },
];
