export const projectAttachments = [
  {
    id: 1,
    fileUrl: "S3_URL/project_1_attachment_1.jpg",
    fileName: "project_1_attachment_1.jpg",
    projectId: 1,
  },
  {
    id: 2,
    fileUrl: "S3_URL/project_1_attachment_2.jpg",
    fileName: "project_1_attachment_2.jpg",
    projectId: 1,
  },
  {
    id: 3,
    fileUrl: "S3_URL/project_2_attachment_1.jpg",
    fileName: "project_2_attachment_1.jpg",
    projectId: 2,
  },
  {
    id: 4,
    fileUrl: "S3_URL/project_2_attachment_2.jpg",
    fileName: "project_2_attachment_2.jpg",
    projectId: 2,
  },
  {
    id: 5,
    fileUrl: "S3_URL/project_3_attachment_1.jpg",
    fileName: "project_3_attachment_1.jpg",
    projectId: 3,
  },
  {
    id: 6,
    fileUrl: "S3_URL/project_3_attachment_2.jpg",
    fileName: "project_3_attachment_2.jpg",
    projectId: 3,
  },
  {
    id: 7,
    fileUrl: "S3_URL/project_4_attachment_1.jpg",
    fileName: "project_4_attachment_1.jpg",
    projectId: 4,
  },
  {
    id: 8,
    fileUrl: "S3_URL/project_4_attachment_2.jpg",
    fileName: "project_4_attachment_2.jpg",
    projectId: 4,
  },
  {
    id: 9,
    fileUrl: "S3_URL/project_5_attachment_1.jpg",
    fileName: "project_5_attachment_1.jpg",
    projectId: 5,
  },
  {
    id: 10,
    fileUrl: "S3_URL/project_5_attachment_2.jpg",
    fileName: "project_5_attachment_2.jpg",
    projectId: 5,
  },
  {
    id: 11,
    fileUrl: "S3_URL/project_6_attachment_1.jpg",
    fileName: "project_6_attachment_1.jpg",
    projectId: 6,
  },
  {
    id: 12,
    fileUrl: "S3_URL/project_6_attachment_2.jpg",
    fileName: "project_6_attachment_2.jpg",
    projectId: 6,
  },
  {
    id: 13,
    fileUrl: "S3_URL/project_7_attachment_1.jpg",
    fileName: "project_7_attachment_1.jpg",
    projectId: 7,
  },
  {
    id: 14,
    fileUrl: "S3_URL/project_7_attachment_2.jpg",
    fileName: "project_7_attachment_2.jpg",
    projectId: 7,
  },
  {
    id: 15,
    fileUrl: "S3_URL/project_8_attachment_1.jpg",
    fileName: "project_8_attachment_1.jpg",
    projectId: 8,
  },
  {
    id: 16,
    fileUrl: "S3_URL/project_8_attachment_2.jpg",
    fileName: "project_8_attachment_2.jpg",
    projectId: 8,
  },
  {
    id: 17,
    fileUrl: "S3_URL/project_9_attachment_1.jpg",
    fileName: "project_9_attachment_1.jpg",
    projectId: 9,
  },
  {
    id: 18,
    fileUrl: "S3_URL/project_9_attachment_2.jpg",
    fileName: "project_9_attachment_2.jpg",
    projectId: 9,
  },
  {
    id: 19,
    fileUrl: "S3_URL/project_10_attachment_1.jpg",
    fileName: "project_10_attachment_1.jpg",
    projectId: 10,
  },
  {
    id: 20,
    fileUrl: "S3_URL/project_10_attachment_2.jpg",
    fileName: "project_10_attachment_2.jpg",
    projectId: 10,
  },
  {
    id: 21,
    fileUrl: "S3_URL/project_11_attachment_1.jpg",
    fileName: "project_11_attachment_1.jpg",
    projectId: 11,
  },
  {
    id: 22,
    fileUrl: "S3_URL/project_11_attachment_2.jpg",
    fileName: "project_11_attachment_2.jpg",
    projectId: 11,
  },
  {
    id: 23,
    fileUrl: "S3_URL/project_12_attachment_1.jpg",
    fileName: "project_12_attachment_1.jpg",
    projectId: 12,
  },
  {
    id: 24,
    fileUrl: "S3_URL/project_12_attachment_2.mp4",
    fileName: "project_12_attachment_2.mp4",
    projectId: 12,
  },
  {
    id: 25,
    fileUrl: "S3_URL/project_13_attachment_1.jpg",
    fileName: "project_13_attachment_1.jpg",
    projectId: 13,
  },
  {
    id: 26,
    fileUrl: "S3_URL/project_13_attachment_2.jpg",
    fileName: "project_13_attachment_2.jpg",
    projectId: 13,
  },
  {
    id: 27,
    fileUrl: "S3_URL/project_14_attachment_1.jpg",
    fileName: "project_14_attachment_1.jpg",
    projectId: 14,
  },
  {
    id: 28,
    fileUrl: "S3_URL/project_14_attachment_2.jpg",
    fileName: "project_14_attachment_2.jpg",
    projectId: 14,
  },
  {
    id: 29,
    fileUrl: "S3_URL/project_15_attachment_1.jpg",
    fileName: "project_15_attachment_1.jpg",
    projectId: 15,
  },
  {
    id: 30,
    fileUrl: "S3_URL/project_15_attachment_2.jpg",
    fileName: "project_15_attachment_2.jpg",
    projectId: 15,
  },
];
