const prefix = `${process.env.S3_ENDPOINT}/${process.env.S3_BUCKET}/`;

export const projectAttachments = [
  {
    id: 1,
    fileUrl: `${prefix}Project1_TechnicalSpecification.docx`,
    fileName: "Project1_TechnicalSpecification.docx",
    projectId: 1,
    workspaceId: 1,
  },
  {
    id: 2,
    fileUrl: `${prefix}Project1_ServicesCatalog.xlsx`,
    fileName: "Project1_ServicesCatalog.xlsx",
    projectId: 1,
    workspaceId: 1,
  },
  {
    id: 3,
    fileUrl: `${prefix}Project2_TechnicalSpecification.docx`,
    fileName: "Project2_TechnicalSpecification.docx",
    projectId: 2,
    workspaceId: 1,
  },
  {
    id: 4,
    fileUrl: `${prefix}Project2_ServicesCatalog.xlsx`,
    fileName: "Project2_ServicesCatalog.xlsx",
    projectId: 2,
    workspaceId: 1,
  },
  {
    id: 5,
    fileUrl: `${prefix}Project3_TechnicalSpecification.docx`,
    fileName: "Project3_TechnicalSpecification.docx",
    projectId: 3,
    workspaceId: 1,
  },
  {
    id: 6,
    fileUrl: `${prefix}Project3_ServicesCatalog.xlsx`,
    fileName: "Project3_ServicesCatalog.xlsx",
    projectId: 3,
    workspaceId: 1,
  },
  {
    id: 7,
    fileUrl: `${prefix}Project4_TechnicalSpecification.docx`,
    fileName: "Project4_TechnicalSpecification.docx",
    projectId: 4,
    workspaceId: 1,
  },
  {
    id: 8,
    fileUrl: `${prefix}Project4_ServicesCatalog.xlsx`,
    fileName: "Project4_ServicesCatalog.xlsx",
    projectId: 4,
    workspaceId: 1,
  },
  {
    id: 9,
    fileUrl: `${prefix}Project5_TechnicalSpecification.docx`,
    fileName: "Project5_TechnicalSpecification.docx",
    projectId: 5,
    workspaceId: 1,
  },
  {
    id: 10,
    fileUrl: `${prefix}Project5_ServicesCatalog.xlsx`,
    fileName: "Project5_ServicesCatalog.xlsx",
    projectId: 5,
    workspaceId: 1,
  },
  {
    id: 11,
    fileUrl: `${prefix}Project6_TechnicalSpecification.docx`,
    fileName: "Project6_TechnicalSpecification.docx",
    projectId: 6,
    workspaceId: 1,
  },
  {
    id: 12,
    fileUrl: `${prefix}Project6_ServicesCatalog.xlsx`,
    fileName: "Project6_ServicesCatalog.xlsx",
    projectId: 6,
    workspaceId: 1,
  },
  {
    id: 13,
    fileUrl: `${prefix}Project7_TechnicalSpecification.docx`,
    fileName: "Project7_TechnicalSpecification.docx",
    projectId: 7,
    workspaceId: 1,
  },
  {
    id: 14,
    fileUrl: `${prefix}Project7_ServicesCatalog.xlsx`,
    fileName: "Project7_ServicesCatalog.xlsx",
    projectId: 7,
    workspaceId: 1,
  },
  {
    id: 15,
    fileUrl: `${prefix}Project8_TechnicalSpecification.docx`,
    fileName: "Project8_TechnicalSpecification.docx",
    projectId: 8,
    workspaceId: 1,
  },
  {
    id: 16,
    fileUrl: `${prefix}Project8_ServicesCatalog.xlsx`,
    fileName: "Project8_ServicesCatalog.xlsx",
    projectId: 8,
    workspaceId: 1,
  },
  {
    id: 17,
    fileUrl: `${prefix}Project9_TechnicalSpecification.docx`,
    fileName: "Project9_TechnicalSpecification.docx",
    projectId: 9,
    workspaceId: 1,
  },
  {
    id: 18,
    fileUrl: `${prefix}Project9_ServicesCatalog.xlsx`,
    fileName: "Project9_ServicesCatalog.xlsx",
    projectId: 9,
    workspaceId: 1,
  },
  {
    id: 19,
    fileUrl: `${prefix}Project10_TechnicalSpecification.docx`,
    fileName: "Project10_TechnicalSpecification.docx",
    projectId: 10,
    workspaceId: 1,
  },
  {
    id: 20,
    fileUrl: `${prefix}Project10_ServicesCatalog.xlsx`,
    fileName: "Project10_ServicesCatalog.xlsx",
    projectId: 10,
    workspaceId: 1,
  },
  {
    id: 21,
    fileUrl: `${prefix}Project11_TechnicalSpecification.docx`,
    fileName: "Project11_TechnicalSpecification.docx",
    projectId: 11,
    workspaceId: 1,
  },
  {
    id: 22,
    fileUrl: `${prefix}Project11_ServicesCatalog.xlsx`,
    fileName: "Project11_ServicesCatalog.xlsx",
    projectId: 11,
    workspaceId: 1,
  },
  {
    id: 23,
    fileUrl: `${prefix}Project12_TechnicalSpecification.docx`,
    fileName: "Project12_TechnicalSpecification.docx",
    projectId: 12,
    workspaceId: 1,
  },
  {
    id: 24,
    fileUrl: `${prefix}Project12_ServicesCatalog.xlsx`,
    fileName: "Project12_ServicesCatalog.xlsx",
    projectId: 12,
    workspaceId: 1,
  },
  {
    id: 25,
    fileUrl: `${prefix}Project13_TechnicalSpecification.docx`,
    fileName: "Project13_TechnicalSpecification.docx",
    projectId: 13,
    workspaceId: 1,
  },
  {
    id: 26,
    fileUrl: `${prefix}Project13_ServicesCatalog.xlsx`,
    fileName: "Project13_ServicesCatalog.xlsx",
    projectId: 13,
    workspaceId: 1,
  },
  {
    id: 27,
    fileUrl: `${prefix}Project14_TechnicalSpecification.docx`,
    fileName: "Project14_TechnicalSpecification.docx",
    projectId: 14,
    workspaceId: 1,
  },
  {
    id: 28,
    fileUrl: `${prefix}Project14_ServicesCatalog.xlsx`,
    fileName: "Project14_ServicesCatalog.xlsx",
    projectId: 14,
    workspaceId: 1,
  },
  {
    id: 29,
    fileUrl: `${prefix}Project15_TechnicalSpecification.docx`,
    fileName: "Project15_TechnicalSpecification.docx",
    projectId: 15,
    workspaceId: 1,
  },
  {
    id: 30,
    fileUrl: `${prefix}Project15_ServicesCatalog.xlsx`,
    fileName: "Project15_ServicesCatalog.xlsx",
    projectId: 15,
    workspaceId: 1,
  },
];
