const prefix = `${process.env.S3_ENDPOINT}/${process.env.S3_BUCKET}/`;

export const taskAttachments = [
  {
    id: 81,
    fileUrl: `${prefix}Task1_TechnicalSpecification.docx`,
    fileName: "Task1_TechnicalSpecification.docx",
    taskId: 1,
    workspaceId: 1,
  },
  {
    id: 82,
    fileUrl: `${prefix}Task1_Summary.docx`,
    fileName: "Task1_Summary.docx",
    taskId: 1,
    workspaceId: 1,
  },
  {
    id: 83,
    fileUrl: `${prefix}Task2_TechnicalSpecification.docx`,
    fileName: "Task2_TechnicalSpecification.docx",
    taskId: 2,
    workspaceId: 1,
  },
  {
    id: 84,
    fileUrl: `${prefix}Task2_Summary.docx`,
    fileName: "Task2_Summary.docx",
    taskId: 2,
    workspaceId: 1,
  },
  {
    id: 85,
    fileUrl: `${prefix}Task3_TechnicalSpecification.docx`,
    fileName: "Task3_TechnicalSpecification.docx",
    taskId: 3,
    workspaceId: 1,
  },
  {
    id: 86,
    fileUrl: `${prefix}Task3_Summary.docx`,
    fileName: "Task3_Summary.docx",
    taskId: 3,
    workspaceId: 1,
  },
  {
    id: 87,
    fileUrl: `${prefix}Task4_TechnicalSpecification.docx`,
    fileName: "Task4_TechnicalSpecification.docx",
    taskId: 4,
    workspaceId: 1,
  },
  {
    id: 88,
    fileUrl: `${prefix}Task4_Summary.docx`,
    fileName: "Task4_Summary.docx",
    taskId: 4,
    workspaceId: 1,
  },
  {
    id: 89,
    fileUrl: `${prefix}Task5_TechnicalSpecification.docx`,
    fileName: "Task5_TechnicalSpecification.docx",
    taskId: 5,
    workspaceId: 1,
  },
  {
    id: 90,
    fileUrl: `${prefix}Task5_Summary.docx`,
    fileName: "Task5_Summary.docx",
    taskId: 5,
    workspaceId: 1,
  },
  {
    id: 91,
    fileUrl: `${prefix}Task6_TechnicalSpecification.docx`,
    fileName: "Task6_TechnicalSpecification.docx",
    taskId: 6,
    workspaceId: 1,
  },
  {
    id: 92,
    fileUrl: `${prefix}Task6_Summary.docx`,
    fileName: "Task6_Summary.docx",
    taskId: 6,
    workspaceId: 1,
  },
  {
    id: 93,
    fileUrl: `${prefix}Task7_TechnicalSpecification.docx`,
    fileName: "Task7_TechnicalSpecification.docx",
    taskId: 7,
    workspaceId: 1,
  },
  {
    id: 94,
    fileUrl: `${prefix}Task7_Summary.docx`,
    fileName: "Task7_Summary.docx",
    taskId: 7,
    workspaceId: 1,
  },
  {
    id: 95,
    fileUrl: `${prefix}Task8_TechnicalSpecification.docx`,
    fileName: "Task8_TechnicalSpecification.docx",
    taskId: 8,
    workspaceId: 1,
  },
  {
    id: 96,
    fileUrl: `${prefix}Task8_Summary.docx`,
    fileName: "Task8_Summary.docx",
    taskId: 8,
    workspaceId: 1,
  },
  {
    id: 97,
    fileUrl: `${prefix}Task9_TechnicalSpecification.docx`,
    fileName: "Task9_TechnicalSpecification.docx",
    taskId: 9,
    workspaceId: 1,
  },
  {
    id: 98,
    fileUrl: `${prefix}Task9_Summary.docx`,
    fileName: "Task9_Summary.docx",
    taskId: 9,
    workspaceId: 1,
  },
  {
    id: 99,
    fileUrl: `${prefix}Task10_TechnicalSpecification.docx`,
    fileName: "Task10_TechnicalSpecification.docx",
    taskId: 10,
    workspaceId: 1,
  },
  {
    id: 100,
    fileUrl: `${prefix}Task10_Summary.docx`,
    fileName: "Task10_Summary.docx",
    taskId: 10,
    workspaceId: 1,
  },
  {
    id: 101,
    fileUrl: `${prefix}Task11_TechnicalSpecification.docx`,
    fileName: "Task11_TechnicalSpecification.docx",
    taskId: 11,
    workspaceId: 1,
  },
  {
    id: 102,
    fileUrl: `${prefix}Task11_Summary.docx`,
    fileName: "Task11_Summary.docx",
    taskId: 11,
    workspaceId: 1,
  },
  {
    id: 103,
    fileUrl: `${prefix}Task12_TechnicalSpecification.docx`,
    fileName: "Task12_TechnicalSpecification.docx",
    taskId: 12,
    workspaceId: 1,
  },
  {
    id: 104,
    fileUrl: `${prefix}Task12_Summary.docx`,
    fileName: "Task12_Summary.docx",
    taskId: 12,
    workspaceId: 1,
  },
  {
    id: 105,
    fileUrl: `${prefix}Task13_TechnicalSpecification.docx`,
    fileName: "Task13_TechnicalSpecification.docx",
    taskId: 13,
    workspaceId: 1,
  },
  {
    id: 106,
    fileUrl: `${prefix}Task13_Summary.docx`,
    fileName: "Task13_Summary.docx",
    taskId: 13,
    workspaceId: 1,
  },
  {
    id: 107,
    fileUrl: `${prefix}Task14_TechnicalSpecification.docx`,
    fileName: "Task14_TechnicalSpecification.docx",
    taskId: 14,
    workspaceId: 1,
  },
  {
    id: 108,
    fileUrl: `${prefix}Task14_Summary.docx`,
    fileName: "Task14_Summary.docx",
    taskId: 14,
    workspaceId: 1,
  },
  {
    id: 109,
    fileUrl: `${prefix}Task15_TechnicalSpecification.docx`,
    fileName: "Task15_TechnicalSpecification.docx",
    taskId: 15,
    workspaceId: 1,
  },
  {
    id: 110,
    fileUrl: `${prefix}Task15_Summary.docx`,
    fileName: "Task15_Summary.docx",
    taskId: 15,
    workspaceId: 1,
  },
  {
    id: 111,
    fileUrl: `${prefix}Task16_TechnicalSpecification.docx`,
    fileName: "Task16_TechnicalSpecification.docx",
    taskId: 16,
    workspaceId: 1,
  },
  {
    id: 112,
    fileUrl: `${prefix}Task16_Summary.docx`,
    fileName: "Task16_Summary.docx",
    taskId: 16,
    workspaceId: 1,
  },
  {
    id: 113,
    fileUrl: `${prefix}Task17_TechnicalSpecification.docx`,
    fileName: "Task17_TechnicalSpecification.docx",
    taskId: 17,
    workspaceId: 1,
  },
  {
    id: 114,
    fileUrl: `${prefix}Task17_Summary.docx`,
    fileName: "Task17_Summary.docx",
    taskId: 17,
    workspaceId: 1,
  },
  {
    id: 115,
    fileUrl: `${prefix}Task18_TechnicalSpecification.docx`,
    fileName: "Task18_TechnicalSpecification.docx",
    taskId: 18,
    workspaceId: 1,
  },
  {
    id: 116,
    fileUrl: `${prefix}Task18_Summary.docx`,
    fileName: "Task18_Summary.docx",
    taskId: 18,
    workspaceId: 1,
  },
  {
    id: 117,
    fileUrl: `${prefix}Task19_TechnicalSpecification.docx`,
    fileName: "Task19_TechnicalSpecification.docx",
    taskId: 19,
    workspaceId: 1,
  },
  {
    id: 118,
    fileUrl: `${prefix}Task19_Summary.docx`,
    fileName: "Task19_Summary.docx",
    taskId: 19,
    workspaceId: 1,
  },
  {
    id: 119,
    fileUrl: `${prefix}Task20_TechnicalSpecification.docx`,
    fileName: "Task20_TechnicalSpecification.docx",
    taskId: 20,
    workspaceId: 1,
  },
  {
    id: 120,
    fileUrl: `${prefix}Task20_Summary.docx`,
    fileName: "Task20_Summary.docx",
    taskId: 20,
    workspaceId: 1,
  },
  {
    id: 121,
    fileUrl: `${prefix}Task21_TechnicalSpecification.docx`,
    fileName: "Task21_TechnicalSpecification.docx",
    taskId: 21,
    workspaceId: 1,
  },
  {
    id: 122,
    fileUrl: `${prefix}Task21_Summary.docx`,
    fileName: "Task21_Summary.docx",
    taskId: 21,
    workspaceId: 1,
  },
  {
    id: 123,
    fileUrl: `${prefix}Task22_TechnicalSpecification.docx`,
    fileName: "Task22_TechnicalSpecification.docx",
    taskId: 22,
    workspaceId: 1,
  },
  {
    id: 124,
    fileUrl: `${prefix}Task22_Summary.docx`,
    fileName: "Task22_Summary.docx",
    taskId: 22,
    workspaceId: 1,
  },
  {
    id: 125,
    fileUrl: `${prefix}Task23_TechnicalSpecification.docx`,
    fileName: "Task23_TechnicalSpecification.docx",
    taskId: 23,
    workspaceId: 1,
  },
  {
    id: 126,
    fileUrl: `${prefix}Task23_Summary.docx`,
    fileName: "Task23_Summary.docx",
    taskId: 23,
    workspaceId: 1,
  },
  {
    id: 127,
    fileUrl: `${prefix}Task24_TechnicalSpecification.docx`,
    fileName: "Task24_TechnicalSpecification.docx",
    taskId: 24,
    workspaceId: 1,
  },
  {
    id: 128,
    fileUrl: `${prefix}Task24_Summary.docx`,
    fileName: "Task24_Summary.docx",
    taskId: 24,
    workspaceId: 1,
  },
  {
    id: 129,
    fileUrl: `${prefix}Task25_TechnicalSpecification.docx`,
    fileName: "Task25_TechnicalSpecification.docx",
    taskId: 25,
    workspaceId: 1,
  },
  {
    id: 130,
    fileUrl: `${prefix}Task25_Summary.docx`,
    fileName: "Task25_Summary.docx",
    taskId: 25,
    workspaceId: 1,
  },
  {
    id: 131,
    fileUrl: `${prefix}Task26_TechnicalSpecification.docx`,
    fileName: "Task26_TechnicalSpecification.docx",
    taskId: 26,
    workspaceId: 1,
  },
  {
    id: 132,
    fileUrl: `${prefix}Task26_Summary.docx`,
    fileName: "Task26_Summary.docx",
    taskId: 26,
    workspaceId: 1,
  },
  {
    id: 133,
    fileUrl: `${prefix}Task27_TechnicalSpecification.docx`,
    fileName: "Task27_TechnicalSpecification.docx",
    taskId: 27,
    workspaceId: 1,
  },
  {
    id: 134,
    fileUrl: `${prefix}Task27_Summary.docx`,
    fileName: "Task27_Summary.docx",
    taskId: 27,
    workspaceId: 1,
  },
  {
    id: 135,
    fileUrl: `${prefix}Task28_TechnicalSpecification.docx`,
    fileName: "Task28_TechnicalSpecification.docx",
    taskId: 28,
    workspaceId: 1,
  },
  {
    id: 136,
    fileUrl: `${prefix}Task28_Summary.docx`,
    fileName: "Task28_Summary.docx",
    taskId: 28,
    workspaceId: 1,
  },
  {
    id: 137,
    fileUrl: `${prefix}Task29_TechnicalSpecification.docx`,
    fileName: "Task29_TechnicalSpecification.docx",
    taskId: 29,
    workspaceId: 1,
  },
  {
    id: 138,
    fileUrl: `${prefix}Task29_Summary.docx`,
    fileName: "Task29_Summary.docx",
    taskId: 29,
    workspaceId: 1,
  },
  {
    id: 139,
    fileUrl: `${prefix}Task30_TechnicalSpecification.docx`,
    fileName: "Task30_TechnicalSpecification.docx",
    taskId: 30,
    workspaceId: 1,
  },
  {
    id: 140,
    fileUrl: `${prefix}Task30_Summary.docx`,
    fileName: "Task30_Summary.docx",
    taskId: 30,
    workspaceId: 1,
  },
  {
    id: 141,
    fileUrl: `${prefix}Task31_TechnicalSpecification.docx`,
    fileName: "Task31_TechnicalSpecification.docx",
    taskId: 31,
    workspaceId: 1,
  },
  {
    id: 142,
    fileUrl: `${prefix}Task31_Summary.docx`,
    fileName: "Task31_Summary.docx",
    taskId: 31,
    workspaceId: 1,
  },
  {
    id: 143,
    fileUrl: `${prefix}Task32_TechnicalSpecification.docx`,
    fileName: "Task32_TechnicalSpecification.docx",
    taskId: 32,
    workspaceId: 1,
  },
  {
    id: 144,
    fileUrl: `${prefix}Task32_Summary.docx`,
    fileName: "Task32_Summary.docx",
    taskId: 32,
    workspaceId: 1,
  },
  {
    id: 145,
    fileUrl: `${prefix}Task33_TechnicalSpecification.docx`,
    fileName: "Task33_TechnicalSpecification.docx",
    taskId: 33,
    workspaceId: 1,
  },
  {
    id: 146,
    fileUrl: `${prefix}Task33_Summary.docx`,
    fileName: "Task33_Summary.docx",
    taskId: 33,
    workspaceId: 1,
  },
  {
    id: 147,
    fileUrl: `${prefix}Task34_TechnicalSpecification.docx`,
    fileName: "Task34_TechnicalSpecification.docx",
    taskId: 34,
    workspaceId: 1,
  },
  {
    id: 148,
    fileUrl: `${prefix}Task34_Summary.docx`,
    fileName: "Task34_Summary.docx",
    taskId: 34,
    workspaceId: 1,
  },
  {
    id: 149,
    fileUrl: `${prefix}Task35_TechnicalSpecification.docx`,
    fileName: "Task35_TechnicalSpecification.docx",
    taskId: 35,
    workspaceId: 1,
  },
  {
    id: 150,
    fileUrl: `${prefix}Task35_Summary.docx`,
    fileName: "Task35_Summary.docx",
    taskId: 35,
    workspaceId: 1,
  },
  {
    id: 151,
    fileUrl: `${prefix}Task36_TechnicalSpecification.docx`,
    fileName: "Task36_TechnicalSpecification.docx",
    taskId: 36,
    workspaceId: 1,
  },
  {
    id: 152,
    fileUrl: `${prefix}Task36_Summary.docx`,
    fileName: "Task36_Summary.docx",
    taskId: 36,
    workspaceId: 1,
  },
  {
    id: 153,
    fileUrl: `${prefix}Task37_TechnicalSpecification.docx`,
    fileName: "Task37_TechnicalSpecification.docx",
    taskId: 37,
    workspaceId: 1,
  },
  {
    id: 154,
    fileUrl: `${prefix}Task37_Summary.docx`,
    fileName: "Task37_Summary.docx",
    taskId: 37,
    workspaceId: 1,
  },
  {
    id: 155,
    fileUrl: `${prefix}Task38_TechnicalSpecification.docx`,
    fileName: "Task38_TechnicalSpecification.docx",
    taskId: 38,
    workspaceId: 1,
  },
  {
    id: 156,
    fileUrl: `${prefix}Task38_Summary.docx`,
    fileName: "Task38_Summary.docx",
    taskId: 38,
    workspaceId: 1,
  },
  {
    id: 161,
    fileUrl: `${prefix}Task41_TechnicalSpecification.docx`,
    fileName: "Task41_TechnicalSpecification.docx",
    taskId: 41,
    workspaceId: 1,
  },
  {
    id: 162,
    fileUrl: `${prefix}Task41_Summary.docx`,
    fileName: "Task41_Summary.docx",
    taskId: 41,
    workspaceId: 1,
  },
  {
    id: 163,
    fileUrl: `${prefix}Task42_TechnicalSpecification.docx`,
    fileName: "Task42_TechnicalSpecification.docx",
    taskId: 42,
    workspaceId: 1,
  },
  {
    id: 164,
    fileUrl: `${prefix}Task42_Summary.docx`,
    fileName: "Task42_Summary.docx",
    taskId: 42,
    workspaceId: 1,
  },
  {
    id: 165,
    fileUrl: `${prefix}Task43_TechnicalSpecification.docx`,
    fileName: "Task43_TechnicalSpecification.docx",
    taskId: 43,
    workspaceId: 1,
  },
  {
    id: 166,
    fileUrl: `${prefix}Task43_Summary.docx`,
    fileName: "Task43_Summary.docx",
    taskId: 43,
    workspaceId: 1,
  },
  {
    id: 167,
    fileUrl: `${prefix}Task44_TechnicalSpecification.docx`,
    fileName: "Task44_TechnicalSpecification.docx",
    taskId: 44,
    workspaceId: 1,
  },
  {
    id: 168,
    fileUrl: `${prefix}Task44_Summary.docx`,
    fileName: "Task44_Summary.docx",
    taskId: 44,
    workspaceId: 1,
  },
  {
    id: 169,
    fileUrl: `${prefix}Task45_TechnicalSpecification.docx`,
    fileName: "Task45_TechnicalSpecification.docx",
    taskId: 45,
    workspaceId: 1,
  },
  {
    id: 170,
    fileUrl: `${prefix}Task45_Summary.docx`,
    fileName: "Task45_Summary.docx",
    taskId: 45,
    workspaceId: 1,
  },
  {
    id: 171,
    fileUrl: `${prefix}Task46_TechnicalSpecification.docx`,
    fileName: "Task46_TechnicalSpecification.docx",
    taskId: 46,
    workspaceId: 1,
  },
  {
    id: 172,
    fileUrl: `${prefix}Task46_Summary.docx`,
    fileName: "Task46_Summary.docx",
    taskId: 46,
    workspaceId: 1,
  },
  {
    id: 173,
    fileUrl: `${prefix}Task47_TechnicalSpecification.docx`,
    fileName: "Task47_TechnicalSpecification.docx",
    taskId: 47,
    workspaceId: 1,
  },
  {
    id: 174,
    fileUrl: `${prefix}Task47_Summary.docx`,
    fileName: "Task47_Summary.docx",
    taskId: 47,
    workspaceId: 1,
  },
  {
    id: 175,
    fileUrl: `${prefix}Task48_TechnicalSpecification.docx`,
    fileName: "Task48_TechnicalSpecification.docx",
    taskId: 48,
    workspaceId: 1,
  },
  {
    id: 176,
    fileUrl: `${prefix}Task48_Summary.docx`,
    fileName: "Task48_Summary.docx",
    taskId: 48,
    workspaceId: 1,
  },
  {
    id: 177,
    fileUrl: `${prefix}Task49_TechnicalSpecification.docx`,
    fileName: "Task49_TechnicalSpecification.docx",
    taskId: 49,
    workspaceId: 1,
  },
  {
    id: 178,
    fileUrl: `${prefix}Task49_Summary.docx`,
    fileName: "Task49_Summary.docx",
    taskId: 49,
    workspaceId: 1,
  },
  {
    id: 179,
    fileUrl: `${prefix}Task50_TechnicalSpecification.docx`,
    fileName: "Task50_TechnicalSpecification.docx",
    taskId: 50,
    workspaceId: 1,
  },
  {
    id: 180,
    fileUrl: `${prefix}Task50_Summary.docx`,
    fileName: "Task50_Summary.docx",
    taskId: 50,
    workspaceId: 1,
  },
  {
    id: 157,
    fileUrl: `${prefix}Task51_TechnicalSpecification.docx`,
    fileName: "Task51_TechnicalSpecification.docx",
    taskId: 51,
    workspaceId: 1,
  },
  {
    id: 158,
    fileUrl: `${prefix}Task51_Summary.docx`,
    fileName: "Task51_Summary.docx",
    taskId: 51,
    workspaceId: 1,
  },
  {
    id: 159,
    fileUrl: `${prefix}Task52_TechnicalSpecification.docx`,
    fileName: "Task52_TechnicalSpecification.docx",
    taskId: 52,
    workspaceId: 1,
  },
  {
    id: 160,
    fileUrl: `${prefix}Task52_Summary.docx`,
    fileName: "Task52_Summary.docx",
    taskId: 52,
    workspaceId: 1,
  },
];
