const prefix = `${process.env.S3_ENDPOINT}/${process.env.S3_BUCKET}/`;

export const users = [
  {
    id: "user-1",
    fullName: "Иван Иванов",
    bio: "Опытный менеджер проекта, специализирующийся на разработке сложных веб-приложений. 5 лет в IT.",
    address: "ул. Тверская, 1, Москва",
    birthdate: new Date("1988-05-15"),
    role: "admin",
    email: "ivan@ws.com",
    emailVerified: true,
    imageUrl: `${prefix}user-1.jpg`,
    phoneNumber: "+7-900-111-22-33",
    publicLink: null,
    positionId: 1,
    createdAt: new Date("2023-01-10T10:00:00Z"),
    workspaceId: 1,
  },
  {
    id: "user-2",
    fullName: "Мария Смирнова",
    bio: "Фронтенд-разработчик с фокусом на React и TypeScript. Обеспечиваю высокий уровень UX/UI.",
    address: "пр. Невский, 25, Санкт-Петербург",
    birthdate: new Date("1995-11-20"),
    role: "user",
    email: "maria@ws.com",
    emailVerified: true,
    imageUrl: `${prefix}user-2.jpg`,
    phoneNumber: "+7-900-222-33-44",
    publicLink: null,
    positionId: 2,
    createdAt: new Date("2023-03-01T11:30:00Z"),
    workspaceId: 1,
  },
  {
    id: "user-3",
    fullName: "Дмитрий Козлов",
    bio: "Старший бэкенд-разработчик на Node.js и Go. Архитектура высоконагруженных систем.",
    address: "ул. Ленина, 50, Екатеринбург",
    birthdate: new Date("1989-08-01"),
    role: "user",
    email: "dmitry@ws.com",
    emailVerified: true,
    imageUrl: `${prefix}user-3.jpg`,
    phoneNumber: "+7-900-333-44-55",
    publicLink: null,
    positionId: 3,
    createdAt: new Date("2023-01-15T09:00:00Z"),
    workspaceId: 1,
  },
  {
    id: "user-4",
    fullName: "Анна Петрова",
    bio: "Ведущий UI/UX дизайнер. Специализируюсь на создании удобных и эстетичных интерфейсов.",
    address: "ул. Пушкина, 10, Казань",
    birthdate: new Date("1993-03-10"),
    role: "user",
    email: "anna@ws.com",
    emailVerified: false,
    imageUrl: `${prefix}user-4.jpg`,
    phoneNumber: "+7-900-444-55-66",
    publicLink: null,
    positionId: 4,
    createdAt: new Date("2023-05-20T14:00:00Z"),
    workspaceId: 1,
  },
  {
    id: "user-5",
    fullName: "Сергей Волков",
    bio: "QA Инженер, ответственный за автоматизацию тестирования и поддержку качества продукта.",
    address: "ул. Кирова, 12, Новосибирск",
    birthdate: new Date("1990-07-04"),
    role: "manager",
    email: "sergey@ws.com",
    emailVerified: true,
    imageUrl: `${prefix}user-5.jpg`,
    phoneNumber: "+7-900-555-66-77",
    publicLink: null,
    positionId: 5,
    createdAt: new Date("2023-02-10T08:30:00Z"),
    workspaceId: 1,
  },
  {
    id: "user-6",
    fullName: "Елена Новикова",
    bio: "Младший менеджер проекта, координирую внутренние коммуникации и отчетность.",
    address: "ул. Гагарина, 30, Самара",
    birthdate: new Date("1996-02-28"),
    role: "user",
    email: "elena@ws.com",
    emailVerified: true,
    imageUrl: `${prefix}user-6.jpg`,
    phoneNumber: "+7-900-666-77-88",
    publicLink: null,
    positionId: 1,
    createdAt: new Date("2023-08-01T13:00:00Z"),
    workspaceId: 1,
  },
  {
    id: "user-7",
    fullName: "Алексей Лебедев",
    bio: "Фронтенд-разработчик (Middle), специализация: Vue.js и оптимизация производительности.",
    address: "ул. Мира, 8, Нижний Новгород",
    birthdate: new Date("1994-04-05"),
    role: "user",
    email: "alexey@ws.com",
    emailVerified: true,
    imageUrl: `${prefix}user-7.jpg`,
    phoneNumber: "+7-900-777-88-99",
    publicLink: null,
    positionId: 2,
    createdAt: new Date("2023-04-10T09:45:00Z"),
    workspaceId: 1,
  },
  {
    id: "user-8",
    fullName: "Ольга Морозова",
    bio: "Бэкенд-разработчик (Junior). Работаю с Python (Django) и PostgreSQL.",
    address: "пр. Октября, 15, Уфа",
    birthdate: new Date("1998-12-07"),
    role: "user",
    email: "olga@ws.com",
    emailVerified: true,
    imageUrl: `${prefix}user-8.jpg`,
    phoneNumber: "+7-900-888-99-00",
    publicLink: null,
    positionId: 3,
    createdAt: new Date("2024-01-20T15:00:00Z"),
    workspaceId: 1,
  },
  {
    id: "user-9",
    fullName: "Павел Соколов",
    bio: "UI/UX Дизайнер. Создание прототипов, тестирование юзабилити. Владею Figma.",
    address: "ул. Красная, 7, Краснодар",
    birthdate: new Date("1991-06-18"),
    role: "user",
    email: "pavel@ws.com",
    emailVerified: true,
    imageUrl: `${prefix}user-9.jpg`,
    phoneNumber: "+7-900-999-00-11",
    publicLink: null,
    positionId: 4,
    createdAt: new Date("2023-06-05T10:15:00Z"),
    workspaceId: 1,
  },
  {
    id: "user-10",
    fullName: "Виктория Зайцева",
    bio: "Специалист по ручному и автоматизированному тестированию. Пишу тесты на Cypress.",
    address: "ул. Калинина, 20, Владивосток",
    birthdate: new Date("1997-04-05"),
    role: "manager",
    email: "viktoria@ws.com",
    emailVerified: true,
    imageUrl: `${prefix}user-10.jpg`,
    phoneNumber: "+7-900-000-11-22",
    publicLink: null,
    positionId: 5,
    createdAt: new Date("2023-10-15T12:40:00Z"),
    workspaceId: 1,
  },
];
